/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Agravante
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Agravante {
  @ApiModelProperty(value = "Abreviatura del agravante")
  private String abrAgr = null;

  @ApiModelProperty(value = "Codigo de agravante. Posibles valores en la tabla [[TRON.EMIS.AGRAVANTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codAgr = null;

  @ApiModelProperty(value = "Codigo de agravante de nivel 1")
  private Integer codAgrNivel1 = null;

  @ApiModelProperty(value = "Codigo de agravante de nivel 2")
  private Integer codAgrNivel2 = null;

  @ApiModelProperty(value = "Codigo de agravante de nivel 3")
  private Integer codAgrNivel3 = null;

  @ApiModelProperty(value = "codigo de agravante de nivel 4")
  private Integer codAgrNivel4 = null;

  @ApiModelProperty(value = "Codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCob = null;

  @ApiModelProperty(value = "Codigo de exclusividad")
  private Integer codExclusivo = null;

  @ApiModelProperty(value = "Codigo del nivel de tramitacion")
  private Integer codNivelAgr = null;

  @ApiModelProperty(value = "Codigo de agrupamiento. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_GRP_AGR]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipGrpAgr = null;

  @ApiModelProperty(value = "Marca que indica si la lista se complementa con datos variables. Posibles valores [S - SE COMPLEMENTA, N - NO SE COMPLEMENTA]")
  private String mcaDatoVariable = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Marca del padre de la estructura. Posibles valores [S - ES EL PADRE, N - NO ES EL PADRE]")
  private String mcaPadre = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de periodo")
  private Integer numPeriodo = null;

  @ApiModelProperty(value = "Numero de póliza.")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Secuencia de la fila")
  private Integer numSecu = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Tasa aplicada al agravante")
  private BigDecimal tasaAgr = null;

  @ApiModelProperty(value = "Accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionBatchEm = null;

  @ApiModelProperty(value = "Tipo de agravante. Posibles valores en la tabla [[TRON.TPES.TIP_AGR]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAgr = null;

  @ApiModelProperty(value = "Tipo de calculo. Posibles valores en la tabla [[TRON.TPES.TIP_CAL_AGR]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCalAgr = null;

  @ApiModelProperty(value = "Codigo de estructura")
  private Integer valPadre = null;



}

