/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * CodAlter
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class CodAlter {
  @ApiModelProperty(value = "Codigo de documento")
  private String codDocum = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Posibles valores [S - Registro inhabilitado, N - Registro habilitado]")
  private String mcaInh = null;

  @ApiModelProperty(value = "Numero secuencia del documento alternativo resultante del proceso")
  private Integer secDocum = null;

  @ApiModelProperty(value = "Numero secuencia del documento de entrada")
  private Integer secDocumEnt = null;

  @ApiModelProperty(value = "Numero de secuencia en origen")
  private Integer secOrigen = null;

  @ApiModelProperty(value = "Código del tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;

  @ApiModelProperty(value = "Codigo del tipo de documento. Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDocum = null;



}

