/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ControlTecnico
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ControlTecnico {
  @ApiModelProperty(value = "Codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCob = null;

  @ApiModelProperty(value = "Codigo de error. Posibles valores en la tabla [[TRON.DATC.ERRORES_CONTROL_TECNICO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codErrorCt = null;

  @ApiModelProperty(value = "Codigo de lista")
  private String codLov = null;

  @ApiModelProperty(value = "Codigo de nivel de control tecnico")
  private Integer codNivelCt = null;

  @ApiModelProperty(value = "Codigo de origen del control tecnico. Posibles valores en la tabla [[TRON.DATC.ORIGEN_ERRORES_CONTROL_TECNICO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codOrigenCt = null;

  @ApiModelProperty(value = "Codigo de usuario que actualiza.")
  private String codUsrAutoriza = null;

  @ApiModelProperty(value = "Fecha en la que se autorizo el ultimo control tecnico. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecAutoriza = null;

  @ApiModelProperty(value = "Marca de error autorizado. Posibles valores [S - AUTORIZADO, N - NO AUTORIZADO]")
  private String mcaAutoriza = null;

  @ApiModelProperty(value = "Marca de autorizacion por defecto si el usuario tiene nivel suficiente. Posibles valores [S - NIVEL SUFICIENTE, N - NO NIVEL SUFICIENTE]")
  private String mcaAutorizaDef = null;

  @ApiModelProperty(value = "Marca que indica si el error se vuelve a controlar en poliza aunque este autorizado en presupuestos (solo si se autorizan errores en presupuestos). Posibles valores [S - SE CONTROLA, N - NO SE CONTROLA]")
  private String mcaNpr = null;

  @ApiModelProperty(value = "Marca que indica el estado de la poliza. Posibles valores [S - PROPUESTA, N - NO POLIZA CONFIRMADA]")
  private String mcaPropuesta = null;

  @ApiModelProperty(value = "Indicador que informa si el control se aplica en propuestas de suplementos. Posibles valores [S - SE APLICA, N - NO SE APLICA]")
  private String mcaPropuestaSuplemento = null;

  @ApiModelProperty(value = "Marca para poder albergar el conjunto de valores definido como ámbito de aplicación del control técnico. Posibles valores [S - SE ALBERGARA, N - NO SE ALBERGARA]")
  private String mcaProyecto = null;

  @ApiModelProperty(value = "Indicador que informa si el control se aplica en proyectos de suplementos. Posibles valores [S - SE APLICA, N - NO SE APLICA]")
  private String mcaProyectoSuplemento = null;

  @ApiModelProperty(value = "Indicador que informa si el control necesita una razon para aplicar el resultado de su ejecucion. Esta marca solo tendra validez para el emisor. Posibles valores [S - NECESITA RAZON, N - NO NECESITA RAZON]")
  private String mcaRazones = null;

  @ApiModelProperty(value = "Marca que indica si error tambien se controla en renovaciones. Posibles valores [S - SE CONTROLA EN RENOVACIONES, N - NO SE CONTROLA EN RENOVACIONES]")
  private String mcaRf = null;

  @ApiModelProperty(value = "Marca que indica si el error tambien se controla en suplementos. Posibles valores [S - SE CONTROLA EN SUPLEMENTOS, N - NO SE CONTROLA EN SUPLEMENTOS]")
  private String mcaSpto = null;

  @ApiModelProperty(value = "Objeto para determinar si se autoriza el error")
  private String nomPrgAutoriza = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de periodo")
  private Integer numPeriodo = null;

  @ApiModelProperty(value = "Numero de póliza.")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Observaciones")
  private String obsAutoriza = null;

  @ApiModelProperty(value = "Tipo de autorización del control técnico (tabla g1010031).  Posibles valores en la tabla [[TRON.TPES.TIP_AUTORIZA_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAutorizaCt = null;

  @ApiModelProperty(value = "Tipo de error. Posibles valores en la tabla [[TRON.TPES.TIP_ERROR_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipErrorCt = null;

  @ApiModelProperty(value = "Tipo de nivel de salto del control tecnico.  Posibles valores en la tabla [[TRON.TPES.TIP_NIVEL_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipNivelCt = null;

  @ApiModelProperty(value = "Descripcion del dato variable")
  private String txtCampo = null;

  @ApiModelProperty(value = "Valor del dato variable")
  private String valCampo = null;



}

