/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Cuenta
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Cuenta {
  @ApiModelProperty(value = "Código actividad propietaria del dato. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codActPropietaria = null;

  @ApiModelProperty(value = "Codigo de aplicacion desde donde se realiza la actualización/inserción")
  private String codApl = null;

  @ApiModelProperty(value = "Código de compañía que accede a este registro de forma exclusiva. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaExclusivo = null;

  @ApiModelProperty(value = "Código de compañía agrupadora. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaGrp = null;

  @ApiModelProperty(value = "Código de compañía propietaria en exclusiva de los datos del tercero. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaPropietaria = null;

  @ApiModelProperty(value = "Código de clase de tarjeta. Posibles valores en la tabla [[TRON.TESO.TARJETAS_CREDITO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codClaseTarjeta = null;

  @ApiModelProperty(value = "Código identificativo del comercio Algunos valores pueden ser: 285601498 285601480 285601530 ... La colección completa de valores del campo se obtiene de la tabla D1001217.")
  private String codComercioTar = null;

  @ApiModelProperty(value = "Código de la entidad bancaria. Sus posibles valores se cargan de la tabla A10013037 y algunos ejemplos son '2038', '2039', '2040'")
  private String codEntidad = null;

  @ApiModelProperty(value = "Código de moneda de la cuenta. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codMonCta = null;

  @ApiModelProperty(value = "Código de la oficina bancaria")
  private String codOficina = null;

  @ApiModelProperty(value = "Código de país. Posibles valores en la tabla [[TRON.DATC.PAISES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codPais = null;

  @ApiModelProperty(value = "Código de tarjeta")
  private Integer codTarjeta = null;

  @ApiModelProperty(value = "Tipo de cuenta bancaria. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_CTA_BCO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipCtaBco = null;

  @ApiModelProperty(value = "Tipo de uso de la cuenta bancaria. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_USO_CTA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipUsoCta = null;

  @ApiModelProperty(value = "Usuario que crea/actualiza el registro")
  private String codUsr = null;

  @ApiModelProperty(value = "Cuenta completa")
  private String cuentaCompleto = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Fecha de vencimiento de la tarjeta. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoTarjeta = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Posibles valores [S - Registro inhabilitado, N - Registro habilitado]")
  private String mcaInh = null;

  @ApiModelProperty(value = "Nombre de la tarjeta")
  private String nomTarjeta = null;

  @ApiModelProperty(value = "Número de la cuenta")
  private String numCta = null;

  @ApiModelProperty(value = "Dígito de control")
  private String numDc = null;

  @ApiModelProperty(value = "Dígito de control del iban")
  private String numDcIban = null;

  @ApiModelProperty(value = "Número de tarjeta")
  private String numTarjeta = null;

  @ApiModelProperty(value = "Secuencia de medio de pago/cobro")
  private Integer secMedioPagocob = null;

  @ApiModelProperty(value = "Secuencia de medio de pago/cobro de entrada")
  private Integer secMedioPagocobEnt = null;

  @ApiModelProperty(value = "Secuencial origen")
  private Integer secOrigen = null;

  @ApiModelProperty(value = "Código del tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;

  @ApiModelProperty(value = "Código del tipo de medio de pago: banco o tarjeta. Posibles valores en la tabla [[TRON.TPES.TIP_MEDIO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMedio = null;

  @ApiModelProperty(value = "Código del tipo de movimiento de la cuenta bancaria. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_CTA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoCta = null;

  @ApiModelProperty(value = "Tipo de movimiento del tercero. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoTercero = null;

  @ApiModelProperty(value = "Codigo de situacion de la validacion del registro por los procesos de depuración de datos. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_VAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituVal = null;

  @ApiModelProperty(value = "Cuenta completa formato papel")
  private String txtCccPapel = null;

  @ApiModelProperty(value = "Cuenta completa formato IBAN electrónico")
  private String txtIbanElectronico = null;

  @ApiModelProperty(value = "Cuenta completa formato IBAN papel")
  private String txtIbanPapel = null;

  @ApiModelProperty(value = "Valor del token tarjeta devuelto por el proveedor de medios de pago")
  private String valTokenTarjet = null;



}

