/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.Comisiones;
import com.capgemini.coedevon.teammanager.prueba.ConceptosEco;
import com.capgemini.coedevon.teammanager.prueba.Cuotas;
import com.capgemini.coedevon.teammanager.prueba.InstalacionCuotas;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * CuotaC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class CuotaC {
  @ApiModelProperty(value = "Cuota")
  private Cuotas cuota = null;

  @ApiModelProperty(value = "Instalacion cuota")
  private InstalacionCuotas instalacionCuota = null;

  @ApiModelProperty(value = "Listado de comisiones")
  private List<Comisiones> listaComisiones = null;

  @ApiModelProperty(value = "Listado de conceptos economicos")
  private List<ConceptosEco> listaConceptosEco = null;



}

