/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * DatoPersonal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class DatoPersonal {
  @ApiModelProperty(value = "Primer apellido del tercero")
  private String ape1Tercero = null;

  @ApiModelProperty(value = "Segundo apellido del tercero")
  private String ape2Tercero = null;

  @ApiModelProperty(value = "Código de actividad de empresa. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES_ECONOMICAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codActEco = null;

  @ApiModelProperty(value = "Código actividad propietaria del dato. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codActPropietaria = null;

  @ApiModelProperty(value = "Codigo de aplicacion desde donde se realiza la actualización/inserción")
  private String codApl = null;

  @ApiModelProperty(value = "Código de compañía propietaria en exclusiva de los datos del tercero. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaPropietaria = null;

  @ApiModelProperty(value = "Código nacional de actividad empresarial. Posibles valores en la tabla [[TRON.TERC.CNAE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codCnae = null;

  @ApiModelProperty(value = "Código del tipo de consentimiento. Posibles valores en la tabla [[TRON.TERC.CONSENTIMIENTO]")
  private String codConsentimiento = null;

  @ApiModelProperty(value = "Código de documento")
  private String codDocum = null;

  @ApiModelProperty(value = "Código de idioma. Necesario para rellenar los campos look up y la descripción de los errores y advertencias. Posibles valores en la tabla [[TRON.DATC.IDIOMAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIdioma = null;

  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Código interno del tercero con el que está relacionado")
  private String codIntCab = null;

  @ApiModelProperty(value = "Clave interna del tercero de entrada")
  private String codIntEnt = null;

  @ApiModelProperty(value = "Clave interna del tercero de la relación")
  private String codIntRelacionTrc = null;

  @ApiModelProperty(value = "International standard industry classification")
  private String codIsic = null;

  @ApiModelProperty(value = "Código de país. Posibles valores en la tabla [[TRON.DATC.PAISES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codNacionalidad = null;

  @ApiModelProperty(value = "Código de ocupación. Posibles valores en la tabla [[TRON.TERC.PROFESIONES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codOcupacion = null;

  @ApiModelProperty(value = "Código de país de nacimiento. Posibles valores en la tabla [[TRON.DATC.PAISES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codPaisNac = null;

  @ApiModelProperty(value = "Código de profesión. Posibles valores en la tabla [[TRON.TERC.PROFESIONES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codProfesion = null;

  @ApiModelProperty(value = "Código de sociedad para consolidación del grupo Mapfre")
  private String codSocGl = null;

  @ApiModelProperty(value = "Código para clasificar al tercero. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_CLASIF_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipClasifTercero = null;

  @ApiModelProperty(value = "Código del tipo de cliente. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_CLIENTE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipCliente = null;

  @ApiModelProperty(value = "Tipo de código nacional de actividad empresarial. Posibles valores en la tabla [[TRON.TERC.CNAE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipCnae = null;

  @ApiModelProperty(value = "Estado civil. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_EST_CIVIL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipEstCivil = null;

  @ApiModelProperty(value = "Estado societario. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ESTADO_SOCIETARIO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipEstadoSocietario = null;

  @ApiModelProperty(value = "Código del tipo de relación entre terceros Posibles valores en la tabla [[TRON.CSTR.COD_TIP_RELACION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipRelacionTrc = null;

  @ApiModelProperty(value = "Código del tipo del segmento del cliente Posibles valores en la tabla [[TRON.CSTR.COD_TIP_SEGMENTO_CLIENTE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipSegmentoCliente = null;

  @ApiModelProperty(value = "Tipo de seguridad a aplicar para recuperar la información de un tercero. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_SEGURIDAD_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipSeguridadTrc = null;

  @ApiModelProperty(value = "Tipo de sociedad. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_SOC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipSoc = null;

  @ApiModelProperty(value = "Tratamiento de relación con el tercero. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_RELACION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipTtoTercero = null;

  @ApiModelProperty(value = "Código del tipo de valor cliente calculado. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_VALOR_CLIENTE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipValorCalc = null;

  @ApiModelProperty(value = "Código de tipo de valor de cliente. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_VALOR_CLIENTE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipValorCliente = null;

  @ApiModelProperty(value = "Código de usuario que realiza la actualización")
  private String codUsr = null;

  @ApiModelProperty(value = "Primer nivel de la estructura de ubicaciones administrativas del país. Para España es el código de la comunidad autónoma de nacimiento. Posibles valores para España en la tabla [[TRON.DATC.COMUNIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codZona1Nac = null;

  @ApiModelProperty(value = "Segundo nivel de la estructura de ubicaciones administrativas del país. Para España es el código de provincia de nacimiento. Posibles valores para España en la tabla [[TRON.DATC.PROVINCIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codZona2Nac = null;

  @ApiModelProperty(value = "Tercer nivel de la estructura de ubicaciones administrativas del país. Para España es el código de localidad de nacimiento. Algunos valores pueden ser: (Con código país = ES y código de zona 2 = 28) 1 - Madrid 53 - Alcalá de Henares 66 - Alcobendas ...")
  private Integer codZona3Nac = null;

  @ApiModelProperty(value = "Secuencial del medio de contacto principal")
  private String contactoCompletoPrc = null;

  @ApiModelProperty(value = "Dirección completa")
  private String dirCompletoHabitual = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha del último balance. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecBalance = null;

  @ApiModelProperty(value = "Fecha de constitución de la empresa. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecCreacionEmpresa = null;

  @ApiModelProperty(value = "Fecha de inicio de operaciones de la empresa. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecIniActividad = null;

  @ApiModelProperty(value = "Fecha de nacimiento")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecNac = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Facturación en euros del cliente empresa")
  private BigDecimal impFacturacion = null;

  @ApiModelProperty(value = "Marca de cancelación parcial S - Cancelación parcial N - No hay cancelación parcial")
  private String mcaCancelacion = null;

  @ApiModelProperty(value = "Insica si el codigo de documento es valido. Posibles valores S - Valido N - No valido")
  private String mcaCodDocumValido = null;

  @ApiModelProperty(value = "Marca femenino. Se considera una marca y no un tipo para evitar ambigüedades en otros países. Posibles valores S - Femenino N - Masculino X - Indeterminado")
  private String mcaFemenino = null;

  @ApiModelProperty(value = "Tipo de persona (física o jurídica): - valor S: Persona física - valor N: Persona jurídica")
  private String mcaFisico = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Posibles valores [S - Registro inhabilitado, N - Registro habilitado]")
  private String mcaInh = null;

  @ApiModelProperty(value = "Tercero que no desea recibir información publicitaria S - Acepta publicidad N - No acepta publicidad")
  private String mcaPublicidad = null;

  @ApiModelProperty(value = "Marca de revocación en la cesión de datos a otras compañías. S - Revoca, N - No revoca")
  private String mcaRevocacion = null;

  @ApiModelProperty(value = "Nombre tercero completo")
  private String nomCompleto = null;

  @ApiModelProperty(value = "Nombre corto del tercero jurídico")
  private String nomCorTercero = null;

  @ApiModelProperty(value = "Nombre del tercero. En el caso de tercero jurídico, el nombre se corresponde con el nombre de la empresa")
  private String nomTercero = null;

  @ApiModelProperty(value = "Número de empleados del cliente empresa")
  private Integer numEmpleados = null;

  @ApiModelProperty(value = "Referencia origen del tercero")
  private String refOrigen = null;

  @ApiModelProperty(value = "Secuencial de la dirección habitual")
  private Integer secDirHabitual = null;

  @ApiModelProperty(value = "")
  private Integer secMedioContactoPrc = null;

  @ApiModelProperty(value = "Código del tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;

  @ApiModelProperty(value = "Código del tipo de documento identificativo. Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDocum = null;

  @ApiModelProperty(value = "Tipo de matriz de empresa. Posibles valores en la tabla [[TRON.TPES.TIP_MATRIZ_GRP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMatrizGrp = null;

  @ApiModelProperty(value = "Tipo de marca de consentimiento de comunicaciones comerciales electrónicas. Posibles valores en la tabla [[TRON.TPES.TIP_MCA_CCCE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMcaCcce = null;

  @ApiModelProperty(value = "Tipo de movimiento del tercero. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoTercero = null;

  @ApiModelProperty(value = "Situación de validez del documento. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_VAL_DOCUM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituValDocum = null;

  @ApiModelProperty(value = "Situación de la validación del nombre por los procesos de depuración de datos. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_VAL_NOM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituValNom = null;

  @ApiModelProperty(value = "Tipo de tercero que se esta gestionando para su tratamiento. Posibles valores en la tabla [[TRON.TPES.TIP_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipTercero = null;

  @ApiModelProperty(value = "Primer nivel de la estructura de ubicaciones administrativas del país. Para España es el texto de la comunidad autónoma de nacimiento. Posibles valores para España en la tabla [[TRON.DATC.COMUNIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String txtZona1Nac = null;

  @ApiModelProperty(value = "Segundo nivel de la estructura de ubicaciones administrativas del país. Para España es el texto de provincia de nacimiento. Posibles valores para España en la tabla [[TRON.DATC.PROVINCIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String txtZona2Nac = null;

  @ApiModelProperty(value = "Tercer nivel de la estructura de ubicaciones administrativas del país. Para España es el texto de localidad de nacimiento. Algunos valores pueden ser: (Con código país = ES y código de zona 2 = 28) 1 - Madrid 53 - Alcalá de Henares 66 - Alcobendas ...")
  private String txtZona3Nac = null;



}

