/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.AutDato;
import com.capgemini.coedevon.teammanager.prueba.CodAlterC;
import com.capgemini.coedevon.teammanager.prueba.ContactoC;
import com.capgemini.coedevon.teammanager.prueba.CuentaC;
import com.capgemini.coedevon.teammanager.prueba.DatoPersonalC;
import com.capgemini.coedevon.teammanager.prueba.DireccionC;
import com.capgemini.coedevon.teammanager.prueba.LicenciaC;
import com.capgemini.coedevon.teammanager.prueba.NomAlterC;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * DDTerceros
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class DDTerceros {
  @ApiModelProperty(value = "Autorizacion Dato")
  private AutDato autDato = null;

  @ApiModelProperty(value = "Datos personal")
  private DatoPersonalC datoPersonal = null;

  @ApiModelProperty(value = "Lista de codigos alternativos")
  private List<CodAlterC> listaCodalter = null;

  @ApiModelProperty(value = "Lista de contactos")
  private List<ContactoC> listaContacto = null;

  @ApiModelProperty(value = "Lista de cuentas")
  private List<CuentaC> listaCuenta = null;

  @ApiModelProperty(value = "Lista de direcciones")
  private List<DireccionC> listaDireccion = null;

  @ApiModelProperty(value = "Lista de licencias")
  private List<LicenciaC> listaLicencia = null;

  @ApiModelProperty(value = "Lista Nombre Alternativo")
  private List<NomAlterC> listaNomalter = null;



}

