/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Direccion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Direccion {
  @ApiModelProperty(value = "Urbanización")
  private String anxDomicilio = null;

  @ApiModelProperty(value = "Número")
  private String atrDomicilio1 = null;

  @ApiModelProperty(value = "Portal")
  private String atrDomicilio2 = null;

  @ApiModelProperty(value = "Piso")
  private String atrDomicilio3 = null;

  @ApiModelProperty(value = "Letra de puerta")
  private String atrDomicilio4 = null;

  @ApiModelProperty(value = "Escalera")
  private String atrDomicilio5 = null;

  @ApiModelProperty(value = "Código actividad propietaria del dato. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codActPropietaria = null;

  @ApiModelProperty(value = "Codigo de aplicacion desde donde se realiza la actualización/inserción")
  private String codApl = null;

  @ApiModelProperty(value = "Código de compañía que accede a este registro de forma exclusiva. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaExclusivo = null;

  @ApiModelProperty(value = "Código de compañía agrupadora. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaGrp = null;

  @ApiModelProperty(value = "Código de compañía propietaria en exclusiva de los datos del tercero. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaPropietaria = null;

  @ApiModelProperty(value = "Código de domicilio normalizado")
  private String codDomicilio = null;

  @ApiModelProperty(value = "Codigo de normalización. Algún valor del campo puede ser: f7 - DIRECCIÓN NORMALIZADA POR DEYDE. IDENTIFICA: POBLACIÓN ACONSEJADA, V�?A Y CÓDIGO POSTAL. FIABILIDAD DIRECCIÓN COMPLETA 95% La colección completa de valores del campo se obtiene de la tabla D1001211")
  private String codNormalizacion = null;

  @ApiModelProperty(value = "Codigo de pais asociado a la cuenta. Posibles valores en la tabla [[TRON.DATC.PAISES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codPais = null;

  @ApiModelProperty(value = "Código de población normalizado")
  private String codPoblacion = null;

  @ApiModelProperty(value = "Codigo postal")
  private String codPostal = null;

  @ApiModelProperty(value = "Código del tipo de dirección. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_DIR]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipDir = null;

  @ApiModelProperty(value = "Código del tipo de domicilio. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_DOMICILIO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipDomicilio = null;

  @ApiModelProperty(value = "Usuario que crea/actualiza el registro")
  private String codUsr = null;

  @ApiModelProperty(value = "Código del primer nivel de la estructura de ubicaciones administrativas del país. Para España es el código de la comunidad autónoma. Posibles valores para España en la tabla [[TRON.DATC.COMUNIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codZona1 = null;

  @ApiModelProperty(value = "Código del segundo nivel de la estructura de ubicaciones administrativas del país. Para España es el código de la provincia. Posibles valores para España en la tabla [[TRON.DATC.PROVINCIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codZona2 = null;

  @ApiModelProperty(value = "Código del tercer nivel de la estructura de ubicaciones administrativas del país. Para España es el código de localidad. Algunos valores pueden ser: (Con código país = ES y código de zona 2 = 28) 1 - Madrid 53 - Alcalá de Henares 66 - Alcobendas ...")
  private Integer codZona3 = null;

  @ApiModelProperty(value = "Dirección completa")
  private String dirCompleto = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Indica si la dirección es extranjera. Posibles valores [S - Si es extranjera, N - No es extranjera]")
  private String mcaExtranjera = null;

  @ApiModelProperty(value = "Indica si se trata de la direccion habitual. Posibles valores [S - Si es habitual, N - No es habitual]")
  private String mcaHabitual = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Posibles valores [S - Registro inhabilitado, N - Registro habilitado]")
  private String mcaInh = null;

  @ApiModelProperty(value = "Nombre del domicilio")
  private String nomDomicilio = null;

  @ApiModelProperty(value = "Texto para zona postal extrajera")
  private String nomPostal = null;

  @ApiModelProperty(value = "Descripción de estado o comunidad autónoma extranjera o nacionales no codificadas")
  private String nomZona1 = null;

  @ApiModelProperty(value = "Descripción provincia extranjera o nacionales no codificadas")
  private String nomZona2 = null;

  @ApiModelProperty(value = "Descripción localidad extranjera o nacionales no codificadas")
  private String nomZona3 = null;

  @ApiModelProperty(value = "Apartado de correos")
  private String numApartado = null;

  @ApiModelProperty(value = "Secuencia de dirección")
  private Integer secDir = null;

  @ApiModelProperty(value = "Secuencia de dirección de entrada")
  private Integer secDirEnt = null;

  @ApiModelProperty(value = "Numero de secuencia en origen")
  private Integer secOrigen = null;

  @ApiModelProperty(value = "Código del tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;

  @ApiModelProperty(value = "Tipo de movimiento del tercero. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoTercero = null;

  @ApiModelProperty(value = "Codigo de situacion de la validacion del registro por los procesos de depuración de datos. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_VAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituVal = null;

  @ApiModelProperty(value = "Linea 1 de la etiqueta para imprimir")
  private String txtEtiqueta1 = null;

  @ApiModelProperty(value = "Linea 2 de la etiqueta")
  private String txtEtiqueta2 = null;

  @ApiModelProperty(value = "Linea 3 de la etiqueta")
  private String txtEtiqueta3 = null;

  @ApiModelProperty(value = "Linea 4 de la etiqueta")
  private String txtEtiqueta4 = null;



}

