/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.Desglose;
import com.capgemini.coedevon.teammanager.prueba.IntervencionPlz;
import com.capgemini.coedevon.teammanager.prueba.ReciboC;
import java.io.IOException;
import java.util.ArrayList;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.List;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * InGeneraSimulacionCV
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class InGeneraSimulacionCV {
  @ApiModelProperty(required = true, value = "Codigo de compañia")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de idioma. Posibles valores en la tabla [[TRON.DATC.IDIOMAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIdioma = null;

  @ApiModelProperty(required = true, value = "Codigo moneda de la poliza. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codMon = null;

  @ApiModelProperty(value = "Código del origen del recibo. Posibles valores en la tabla [[TRON.EMIS.ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codOrigenRecibo = null;

  @ApiModelProperty(required = true, value = "Codigo plan de pago. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codPlanPago = null;

  @ApiModelProperty(required = true, value = "Código de ramo. Posibles valores en la tabla [[TRON.EMIS.RAMOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codRamo = null;

  @ApiModelProperty(value = "Código del sistema de emisión del recibo. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipOrigenRecibo = null;

  @ApiModelProperty(required = true, value = "Código de usuario")
  private String codUsr = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(required = true, value = "Fecha de efecto del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecSpto = null;

  @ApiModelProperty(required = true, value = "Fecha de emisión del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEmSpto = null;

  @ApiModelProperty(required = true, value = "Fecha de vencimiento del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoSpto = null;

  @ApiModelProperty(value = "Lista Desglose")
  private List<Desglose> listaDesglose = null;

  @ApiModelProperty(required = true, value = "Lista invervenciones de los pagadores")
  private List<IntervencionPlz> listaIntervPagadores = new ArrayList<IntervencionPlz>();

  @ApiModelProperty(value = "Listado de recibos complejo")
  private List<ReciboC> listaReciboC = null;

  @ApiModelProperty(required = true, value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero decimales comisiones")
  private Integer numDecCom = null;

  @ApiModelProperty(value = "Numero decimales recibo")
  private Integer numDecRecibo = null;

  @ApiModelProperty(value = "Numero de movimiento de comisiones")
  private Integer numMvtoCom = null;

  @ApiModelProperty(value = "Numero de movimiento de emision para cambio de forma de pago, de agente, etc.")
  private Integer numMvtoEm = null;

  @ApiModelProperty(value = "Número total de periodos de la póliza")
  private Integer numPeriodos = null;

  @ApiModelProperty(required = true, value = "Numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Tipo coaseguro (0)sin coaseguro (1)cedido (2)aceptado. Posibles valores en la tabla [[TRON.TPES.TIP_COA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCoa = null;

  @ApiModelProperty(value = "Tipo de suplemento. Posibles valores en la tabla [[TRON.TPES.TIP_SPTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSpto = null;

  @ApiModelProperty(value = "Tipo de cambio")
  private Integer valCambio = null;



}

