/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * InstalacionCuotas
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class InstalacionCuotas {
  @ApiModelProperty(value = "Fecha proximo vencimiento de recibo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecProxVtoReciboMut = null;

  @ApiModelProperty(value = "Indica si es una cuota a regularizar. Posibles valores S - se debe regularizae, N - no debe regularizar")
  private String mcaCuotaDeRegularizMut = null;

  @ApiModelProperty(value = "Indica si es una cuota a eliminar. Posibles valores S - si es a eliminar, N - no es a eliminar")
  private String mcaCuotaQueEliminaMut = null;

  @ApiModelProperty(value = "Indica si es posible la reserva de prima. Posibles valores S - si es posible, N - no es posible")
  private String mcaPosRsvaPrimasMut = null;

  @ApiModelProperty(value = "Indica si la prima esta reservada. Posibles valores S - reservada, N - no reseravda")
  private String mcaPrimaReservadaMut = null;

  @ApiModelProperty(value = "Número de cuota")
  private Integer numCuota = null;

  @ApiModelProperty(value = "Numero de recibo")
  private Long numRecibo = null;

  @ApiModelProperty(value = "Numero anexo aplicación AB")
  private Integer numSitAnexoApliAbMut = null;

  @ApiModelProperty(value = "Numero anexo aplicación CA")
  private Integer numSitAnexoApliCaMut = null;



}

