/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.Agravante;
import com.capgemini.coedevon.teammanager.prueba.Clausula;
import com.capgemini.coedevon.teammanager.prueba.Coaseguro;
import com.capgemini.coedevon.teammanager.prueba.Cobertura;
import com.capgemini.coedevon.teammanager.prueba.CodOrigenRecibo;
import com.capgemini.coedevon.teammanager.prueba.Comisiones;
import com.capgemini.coedevon.teammanager.prueba.ConceptosEco;
import com.capgemini.coedevon.teammanager.prueba.ControlTecnico;
import com.capgemini.coedevon.teammanager.prueba.Cuotas;
import com.capgemini.coedevon.teammanager.prueba.DDTerceros;
import com.capgemini.coedevon.teammanager.prueba.Desglose;
import com.capgemini.coedevon.teammanager.prueba.FecExtraccionRecibo;
import com.capgemini.coedevon.teammanager.prueba.FranquiciaCob;
import com.capgemini.coedevon.teammanager.prueba.GcPolizas;
import com.capgemini.coedevon.teammanager.prueba.GcRecibos;
import com.capgemini.coedevon.teammanager.prueba.GcTerceros;
import com.capgemini.coedevon.teammanager.prueba.InfAdicional;
import com.capgemini.coedevon.teammanager.prueba.InfAdicionalAgr;
import com.capgemini.coedevon.teammanager.prueba.InfAdicionalOcu;
import com.capgemini.coedevon.teammanager.prueba.InfGeneral;
import com.capgemini.coedevon.teammanager.prueba.InstalacionCuotas;
import com.capgemini.coedevon.teammanager.prueba.InstalacionPoliza;
import com.capgemini.coedevon.teammanager.prueba.InstalacionRecibos;
import com.capgemini.coedevon.teammanager.prueba.InstalacionRiesgo;
import com.capgemini.coedevon.teammanager.prueba.IntervAgt;
import com.capgemini.coedevon.teammanager.prueba.IntervDep;
import com.capgemini.coedevon.teammanager.prueba.IntervencionPlz;
import com.capgemini.coedevon.teammanager.prueba.LimiteCob;
import com.capgemini.coedevon.teammanager.prueba.LineaTexto;
import com.capgemini.coedevon.teammanager.prueba.Ocurrencia;
import com.capgemini.coedevon.teammanager.prueba.Periodo;
import com.capgemini.coedevon.teammanager.prueba.PlanPago;
import com.capgemini.coedevon.teammanager.prueba.RecibosGrupo;
import com.capgemini.coedevon.teammanager.prueba.RecibosPrima;
import com.capgemini.coedevon.teammanager.prueba.RecibosSinPrima;
import com.capgemini.coedevon.teammanager.prueba.Riesgo;
import com.capgemini.coedevon.teammanager.prueba.SateliteRiesgo;
import com.capgemini.coedevon.teammanager.prueba.SateliteSpto;
import com.capgemini.coedevon.teammanager.prueba.Texto;
import com.capgemini.coedevon.teammanager.prueba.TipEmiRecibo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * InTraspasarPoliza
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class InTraspasarPoliza {
  @ApiModelProperty(required = true, value = "Codigo de compañia")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de idioma. Posibles valores en la tabla [[TRON.DATC.IDIOMAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIdioma = null;

  @ApiModelProperty(value = "Código de origen del recibo. Posibles valores en la tabla [[TRON.EMIS.ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipOrigenRecibo = null;

  @ApiModelProperty(value = "Código de usuario")
  private String codUsr = null;

  @ApiModelProperty(required = true, value = "Información general de la poliza")
  private InfGeneral infGeneral = null;

  @ApiModelProperty(value = "Lista Agravante")
  private List<Agravante> listaAgravante = null;

  @ApiModelProperty(value = "Lista Clausula")
  private List<Clausula> listaClausula = null;

  @ApiModelProperty(value = "Lista coaseguros")
  private List<Coaseguro> listaCoaseguro = null;

  @ApiModelProperty(value = "Lista de coberturas")
  private List<Cobertura> listaCobertura = null;

  @ApiModelProperty(value = "Listado de códigos de origen del recibo")
  private List<CodOrigenRecibo> listaCodOrigenRecibo = null;

  @ApiModelProperty(value = "Listado de comisiones")
  private List<Comisiones> listaComisiones = null;

  @ApiModelProperty(value = "Listado de conceptos economicos")
  private List<ConceptosEco> listaConceptosEco = null;

  @ApiModelProperty(value = "Lista Control Tecnico")
  private List<ControlTecnico> listaControlTecnico = null;

  @ApiModelProperty(value = "Listado de cuotas")
  private List<Cuotas> listaCuotas = null;

  @ApiModelProperty(value = "Lista de Datos de Terceros")
  private List<DDTerceros> listaDDTerceros = null;

  @ApiModelProperty(value = "Lista Desglose")
  private List<Desglose> listaDesglose = null;

  @ApiModelProperty(value = "Listado de fechas de extracción de recibos")
  private List<FecExtraccionRecibo> listaFecExtraccionRecibo = null;

  @ApiModelProperty(value = "Lista de franquicias por coberturas")
  private List<FranquiciaCob> listaFranquiciaCob = null;

  @ApiModelProperty(value = "Lista de informacion adicional")
  private List<InfAdicional> listaInfAdicional = null;

  @ApiModelProperty(value = "Lista informacion adicional Agravante")
  private List<InfAdicionalAgr> listaInfAdicionalAgr = null;

  @ApiModelProperty(value = "Lista de informacion de ocurrencias")
  private List<InfAdicionalOcu> listaInfAdicionalOcu = null;

  @ApiModelProperty(value = "Listado de instalación cuotas")
  private List<InstalacionCuotas> listaInstalacionCuotas = null;

  @ApiModelProperty(value = "Lista Instalacion Poliza")
  private List<InstalacionPoliza> listaInstalacionPoliza = null;

  @ApiModelProperty(value = "Listado de instalacion recibos")
  private List<InstalacionRecibos> listaInstalacionRecibos = null;

  @ApiModelProperty(value = "Lista Instalacion Riesgo")
  private List<InstalacionRiesgo> listaInstalacionRiesgo = null;

  @ApiModelProperty(value = "Lista Intervencion de agentes")
  private List<IntervAgt> listaIntervAgt = null;

  @ApiModelProperty(value = "Lista de intervenciones dependientes")
  private List<IntervDep> listaIntervDep = null;

  @ApiModelProperty(value = "Lista de intervencion Poliza")
  private List<IntervencionPlz> listaIntervencionPlz = null;

  @ApiModelProperty(value = "Lista de limites por coberturas")
  private List<LimiteCob> listaLimiteCob = null;

  @ApiModelProperty(value = "Lista de linea de textos")
  private List<LineaTexto> listaLineaTexto = null;

  @ApiModelProperty(value = "Lista de ocurrencias")
  private List<Ocurrencia> listaOcurrencia = null;

  @ApiModelProperty(value = "Lista de Periodo")
  private List<Periodo> listaPeriodo = null;

  @ApiModelProperty(value = "Lista plan pago")
  private List<PlanPago> listaPlanPago = null;

  @ApiModelProperty(value = "Listado de polizas")
  private List<GcPolizas> listaPolizas = null;

  @ApiModelProperty(value = "Listado de recibos")
  private List<GcRecibos> listaRecibos = null;

  @ApiModelProperty(value = "Listado de recibos grupo")
  private List<RecibosGrupo> listaRecibosGrupo = null;

  @ApiModelProperty(value = "Listado de recibos prima")
  private List<RecibosPrima> listaRecibosPrima = null;

  @ApiModelProperty(value = "Listado de recibos sin prima")
  private List<RecibosSinPrima> listaRecibosSinPrima = null;

  @ApiModelProperty(value = "Lista de Riesgos")
  private List<Riesgo> listaRiesgo = null;

  @ApiModelProperty(value = "Lista Satelite Riesgo")
  private List<SateliteRiesgo> listaSateliteRiesgo = null;

  @ApiModelProperty(value = "Listado de recibos")
  private List<GcTerceros> listaTerceros = null;

  @ApiModelProperty(value = "Lista de textos")
  private List<Texto> listaTexto = null;

  @ApiModelProperty(value = "Listado de tipos de emisión del recibo")
  private List<TipEmiRecibo> listaTipEmiRecibo = null;

  @ApiModelProperty(value = "Marca de agrupación de cuota. Posibles valores S o N.")
  private String mcaAgrupacionCuota = null;

  @ApiModelProperty(value = "Marca de reserva de primas. Posibles valores [S - prima reservada , N - prima no reservada].")
  private String mcaConstitucionDto = null;

  @ApiModelProperty(value = "Indicador de cuotas manuales. Posibles valores [S - Cuota Manual o N - Cuota no manual]")
  private String mcaCuotasManual = null;

  @ApiModelProperty(value = "Marca para indicar si se modifica un dato común en un tercero revocado. Posibles valores [S - se modifica , N - no se modifica].")
  private String mcaModifCorrectiva = null;

  @ApiModelProperty(value = "Marca que indica si se llamará a la lógica que numera y graba los recibos. Posibles valores [S - Se invoca a la logica, N - No se invoca a la logica]")
  private String mcaNumeraRecibo = null;

  @ApiModelProperty(required = true, value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(required = true, value = "Numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(required = true, value = "Nnúmero identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(required = true, value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Satelite Suplemento")
  private SateliteSpto sateliteSpto = null;

  @ApiModelProperty(value = "Tipo de proceso si se trata de un proceso batch. En on-line su valor es nulo. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_BATCH]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoBatch = null;

  @ApiModelProperty(value = "Tipo sesion")
  private String tipSesion = null;



}

