/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Licencia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Licencia {
  @ApiModelProperty(value = "Abreviatura del la licencia")
  private String abrLicencia = null;

  @ApiModelProperty(value = "Codigo de actividad de los terceros")
  private Integer codActPropietaria = null;

  @ApiModelProperty(value = "Codigo de aplicacion desde donde se realiza la actualizacion/insercion. Posibles valores en la tabla [[RIC.APLI.APLICACIONES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codApl = null;

  @ApiModelProperty(value = "Codigo de compañia este codigo se utilizara cuando el contacto sea exclusivo de una compañia, permitiendo asi poder almacenar informacion de contactos asociados a distintas compañias. en la mayoria de los casos un tercero no tendra contactos o el contacto sera de todas las entidades y este campo no llevara valor.")
  private Integer codCiaExclusivo = null;

  @ApiModelProperty(value = "Codigo compañia agrupadora sobre la que aplica excepcion. 99 es para todas las compañias")
  private Integer codCiaGrp = null;

  @ApiModelProperty(value = "Código de compañía propietaria en exclusiva de los datos del tercero")
  private Integer codCiaPropietaria = null;

  @ApiModelProperty(value = "Codigo de licencia")
  private String codLicencia = null;

  @ApiModelProperty(value = "Tipo de licencia. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_LICENCIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipLicencia = null;

  @ApiModelProperty(value = "Codigo de usuario")
  private String codUsr = null;

  @ApiModelProperty(value = "Fecha de actualizacion. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha de expedicion de la licencia. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecExpLicencia = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Licencia completa")
  private String licenciaCompleto = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Numero de licencia")
  private String numLicencia = null;

  @ApiModelProperty(value = "Observaciones que se quieran especificar la licencia")
  private String obsLicencia = null;

  @ApiModelProperty(value = "Secuencia de la licencia ( orden )")
  private Integer secLicencia = null;

  @ApiModelProperty(value = "Secuencia de la licencia de entrada")
  private Integer secLicenciaEnt = null;

  @ApiModelProperty(value = "Secuencial origen, 0 en registro de datos personales (dp)")
  private Integer secOrigen = null;

  @ApiModelProperty(value = "Accion a realizar con el registro de datos de terceros. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;

  @ApiModelProperty(value = "Tipo de movimiento del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_MVTO_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoTercero = null;



}

