/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Ocurrencia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Ocurrencia {
  @ApiModelProperty(value = "Abreviatura de lista de ocurrencias")
  private String abrListaOcu = null;

  @ApiModelProperty(value = "Atributo")
  private String atrOcu1 = null;

  @ApiModelProperty(value = "Atributo")
  private String atrOcu2 = null;

  @ApiModelProperty(value = "Atributo")
  private String atrOcu3 = null;

  @ApiModelProperty(value = "Atributo")
  private String atrOcu4 = null;

  @ApiModelProperty(value = "Codigo de campo de valor almacenado. Posibles valores en la tabla [[TRON.EMIS.DATOS_VARIABLES_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codCampo = null;

  @ApiModelProperty(value = "Codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCob = null;

  @ApiModelProperty(value = "Codigo de documento")
  private String codDocum = null;

  @ApiModelProperty(value = "Codigo identificacion tratamiento del tercero(dentro de terceros)")
  private String codIdentificacion = null;

  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Codigo de lista")
  private Integer codListaOcu = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Suma asegurada")
  private BigDecimal impCap = null;

  @ApiModelProperty(value = "Importe correspondiente al dato variable")
  private BigDecimal impOcu = null;

  @ApiModelProperty(value = "Marca que indica si cada ocurrencia de la lista calcula prima. Posibles valores [S - CALCULA PRIMA, N - NO CALCULA PRIMA]")
  private String mcaCalOcu = null;

  @ApiModelProperty(value = "Marca que indica si la lista se complementa con datos variables. Posibles valores [S - COMPLEMENTA, N - NO COMPLEMENTA]")
  private String mcaDatoVariable = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Nombre del animal")
  private String nomAnimal = null;

  @ApiModelProperty(value = "Nombre de la clave de producción")
  private String nomCompleto = null;

  @ApiModelProperty(value = "Nombre del obejto")
  private String nomObjeto = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de ocurrencia dentro de la lista")
  private Integer numOcu = null;

  @ApiModelProperty(value = "Numero de periodo")
  private Integer numPeriodo = null;

  @ApiModelProperty(value = "Numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Secuencia de la fila")
  private Integer numSecuOcu = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionBatchEm = null;

  @ApiModelProperty(value = "Codigo del tipo de documento dni,nif,.... Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDocum = null;

  @ApiModelProperty(value = "Codigo de lista. Posibles valores en la tabla [[TRON.TPES.TIP_LISTA_OCU]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipListaOcu = null;

  @ApiModelProperty(value = "Tipo de modelo (n-normal, e-encriptado, p-personalizado)")
  private String tipModel = null;



}

