/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestTrcDdContactoS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestTrcDdContactoS {
  @ApiModelProperty(value = "Código actividad propietaria del dato. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codActPropietaria = null;

  @ApiModelProperty(value = "Codigo de aplicacion desde donde se realiza la actualización/inserción")
  private String codApl = null;

  @ApiModelProperty(value = "Código de compañía que accede a este registro de forma exclusiva. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaExclusivo = null;

  @ApiModelProperty(value = "Código de compañía agrupadora. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaGrp = null;

  @ApiModelProperty(value = "Código de compañía propietaria en exclusiva de los datos del tercero. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaPropietaria = null;

  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Código del tipo de uso que se le va a dar al medio de contacto. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_USO_CONTACTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipUsoContacto = null;

  @ApiModelProperty(value = "Usuario que crea/actualiza el registro")
  private String codUsr = null;

  @ApiModelProperty(value = "Medio de contacto completo")
  private String contactoCompleto = null;

  @ApiModelProperty(value = "Dirección completa")
  private String dirCompleto = null;

  @ApiModelProperty(value = "Dirección email")
  private String dirEmail = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Posibles valores [S - Registro inhabilitado, N - Registro habilitado]")
  private String mcaInh = null;

  @ApiModelProperty(value = "Indica si el tercero es principal. Posibles valores [S - Si es principal, N - No es principal]")
  private String mcaPrincipal = null;

  @ApiModelProperty(value = "Descripción asociada al código actividad propietaria del dato. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomActPropietaria = null;

  @ApiModelProperty(value = "Descripción del cargo que ocupa el contacto")
  private String nomCargo = null;

  @ApiModelProperty(value = "Descripción del código de compañía que accede a este registro de forma exclusiva. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaExclusivo = null;

  @ApiModelProperty(value = "Descripción del código de compañía agrupadora. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaGrp = null;

  @ApiModelProperty(value = "Descripción asociada al código de compañía propietaria en exclusiva de los datos del tercero. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaPropietaria = null;

  @ApiModelProperty(value = "Tipo de uso que se le va a dar al medio de contacto. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_USO_CONTACTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipUsoContacto = null;

  @ApiModelProperty(value = "Nombre de la persona con la que se va a contactar")
  private String nomContacto = null;

  @ApiModelProperty(value = "Departamento del contacto")
  private String nomDpto = null;

  @ApiModelProperty(value = "Tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccionTrc = null;

  @ApiModelProperty(value = "Descripción asociada al tipo de movimiento del tercero. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipMvtoTercero = null;

  @ApiModelProperty(value = "Situacion de la validacion del registro por los procesos de depuración de datos. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_VAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipSituVal = null;

  @ApiModelProperty(value = "Número de busca")
  private String numBusca = null;

  @ApiModelProperty(value = "Número de fax")
  private String numFax = null;

  @ApiModelProperty(value = "Observaciones")
  private String obs = null;

  @ApiModelProperty(value = "Dirección de la página web")
  private String pagWeb = null;

  @ApiModelProperty(value = "Secuencia de direccion")
  private Integer secDir = null;

  @ApiModelProperty(value = "Secuencia de medio de contacto")
  private Integer secMedioContacto = null;

  @ApiModelProperty(value = "Secuencia de medio de contacto de entrada")
  private Integer secMedioContactoEnt = null;

  @ApiModelProperty(value = "NUMERO DE SECUENCIA EN ORIGEN")
  private Integer secOrigen = null;

  @ApiModelProperty(value = "Código del tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;

  @ApiModelProperty(value = "Tipo de movimiento del tercero. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_TERCERO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoTercero = null;

  @ApiModelProperty(value = "Codigo de situacion de la validacion del registro por los procesos de depuración de datos. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_VAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituVal = null;

  @ApiModelProperty(value = "Extensión telefónica")
  private String tlfExt = null;

  @ApiModelProperty(value = "Teléfono móvil")
  private String tlfMovil = null;

  @ApiModelProperty(value = "Número del teléfono")
  private String tlfNum = null;

  @ApiModelProperty(value = "Prefijo del pais del teléfono")
  private String tlfPais = null;

  @ApiModelProperty(value = "Prefijo de la zona del teléfono")
  private String tlfZona = null;



}

