/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestPlzCoberturaS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestPlzCoberturaS {
  @ApiModelProperty(value = "Abreviatura de la cobertura")
  private String abrCob = null;

  @ApiModelProperty(value = "Año base para la regularizacion de capitales en renovacion")
  private Integer anioBaseRevaloriza = null;

  @ApiModelProperty(value = "Atributo 1 de la cobertura")
  private Integer atrCob1 = null;

  @ApiModelProperty(value = "Atributo 2 de la cobertura")
  private Integer atrCob2 = null;

  @ApiModelProperty(value = "Atributo 3 de la cobertura")
  private Integer atrCob3 = null;

  @ApiModelProperty(value = "Atributo 4 de la cobertura")
  private Integer atrCob4 = null;

  @ApiModelProperty(value = "Atributo 5 de la cobertura")
  private Integer atrCob5 = null;

  @ApiModelProperty(value = "Atributo 6 de la cobertura")
  private Integer atrCob6 = null;

  @ApiModelProperty(value = "Codigo de campo de valor almacenado. Posibles valores en la tabla [[TRON.EMIS.DATOS_VARIABLES_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codCampo = null;

  @ApiModelProperty(value = "Codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCob = null;

  @ApiModelProperty(value = "Codigo de cobertura relacionada (dependientes e independientes). Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCobRel = null;

  @ApiModelProperty(value = "Codigo de franquicia o deducible")
  private Integer codFranquicia = null;

  @ApiModelProperty(value = "Codigo de la franquicia de origen")
  private Integer codFranquiciaOrigen = null;

  @ApiModelProperty(value = "Codigo de agrupamiento")
  private Integer codGrpAcc = null;

  @ApiModelProperty(value = "Codigo de agrupamiento de coberturas")
  private String codGrpCob1 = null;

  @ApiModelProperty(value = "Codigo de agrupamiento 2 de coberturas .")
  private String codGrpCob2 = null;

  @ApiModelProperty(value = "Codigo de agrupamiento 3 de coberturas .")
  private String codGrpCob3 = null;

  @ApiModelProperty(value = "Codigo de agrupamiento 4 de coberturas .")
  private String codGrpCob4 = null;

  @ApiModelProperty(value = "Codigo del indice de revalorizacion. Posibles valores en la tabla [[TRON.EMIS.INDICES_REFERENCIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codIndice = null;

  @ApiModelProperty(value = "Codigo de limite")
  private Integer codLimite = null;

  @ApiModelProperty(value = "Codigo limite de origen")
  private Integer codLimiteOrigen = null;

  @ApiModelProperty(value = "Codigo de lista")
  private Integer codListaOcu = null;

  @ApiModelProperty(value = "Codigo de moneda del capital. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codMonImpCap = null;

  @ApiModelProperty(value = "Ramo contable")
  private String codRamoCtable = null;

  @ApiModelProperty(value = "Fecha de efecto. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecCob = null;

  @ApiModelProperty(value = "Fecha de efecto de la franquicia. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecFranquicia = null;

  @ApiModelProperty(value = "Fecha de vencimiento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoCob = null;

  @ApiModelProperty(value = "Fecha de vencimiento de la franquicia. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVtoFranquicia = null;

  @ApiModelProperty(value = "Suma asegurada")
  private BigDecimal impCap = null;

  @ApiModelProperty(value = "Suma asegurada de baja por siniestro")
  private BigDecimal impCapBajaSini = null;

  @ApiModelProperty(value = "Importe de los accesorios que se han dado de baja por siniestro")
  private BigDecimal impCapBajaSiniAcc = null;

  @ApiModelProperty(value = "Importe de la lista de valores que se han dado de baja por siniestro")
  private BigDecimal impCapBajaSiniLista = null;

  @ApiModelProperty(value = "Suma asegurada limite superior en caso de dos limites")
  private BigDecimal impCapMaxStdad = null;

  @ApiModelProperty(value = "Suma asegurada del suplemento")
  private BigDecimal impCapSpto = null;

  @ApiModelProperty(value = "Importe del suplemento de origen")
  private BigDecimal impCapSptoOrigen = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura puede tener o no accesorios.. Posibles valores [S - PUEDE TENER ACCESORIOS, N - NO PUEDE TENER ACCESORIOS]")
  private String mcaAcc = null;

  @ApiModelProperty(value = "Indica si es agravante. Posibles valores [S - ES AGRAVANTE, N - NO ES AGRAVANTE] ")
  private String mcaAgr = null;

  @ApiModelProperty(value = "Marca que indica si la suma asegurada se va agotando por los siniestros sufridos. Posibles valores [S - SE AGOTA, N - NO SE AGOTA]")
  private String mcaBajaImpCapSini = null;

  @ApiModelProperty(value = "Marca que si afecta al calculo de las bonificaciones. Posibles valores [S - AFECTA, N - NO AFECTA]")
  private String mcaBoni = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura es consorciable. Posibles valores [S - CONSORCIABLE, N - NO CONSORCIABLE]")
  private String mcaCobConsor = null;

  @ApiModelProperty(value = "Marca de cobertura de la poliza. Posibles valores [S - COBERTURA DE LA POLIZA, N - NO COBERTURA DE LA POLIZA]")
  private String mcaCobPoliza = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura tiene comisiones en la cartera. Posibles valores [S - TIENE COMISIONES, N - NO TIENE COMISIONES]")
  private String mcaComCar = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura tiene comisiones en nueva produccion. Posibles valores [S - TIENE COMISIONES, N - NO TIENE COMISIONES]")
  private String mcaComNpr = null;

  @ApiModelProperty(value = "Marca que indica si la lista se complementa con datos variables. Posibles valores [S - SE COMPLEMENTA, N - NO SE COMPLEMENTA]")
  private String mcaDatoVariable = null;

  @ApiModelProperty(value = "Marca que indica si la revalorizacion, actua como depreciacion. Posibles valores [S - DEPRECIA, N - NO DEPRECIA]")
  private String mcaDeprecia = null;

  @ApiModelProperty(value = "Marca que indica la posibilidad de emitir utilizando este ramo. Posibles valores [S - SE PUEDE EMITIR, N - NO SE PUEDE EMITIR]")
  private String mcaEm = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura puede tener o no franquicias.. Posibles valores [S - PUEDE TENER FRANQUICIAS, N - PUEDE NO TENER FRANQUICIAS]")
  private String mcaFranquicia = null;

  @ApiModelProperty(value = "Marca de franquicia manual. indica si se permitira introducir el valor de forma manual en la peticion de la franquicia. Posibles valores [S - FORMA MANUAL, N - NO FORMA MANUAL]")
  private String mcaFranquiciaManual = null;

  @ApiModelProperty(value = "Marca de impresion obligatoria. Indica que la cobertura debe imprimirse en las condiciones particulares.. Posibles valores [S - IMPRESION OBLIGATORIA, N - IMPRESION NO OBLIGATORIA]")
  private String mcaImpObl = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Marca de si se da de baja la cobertura. Posibles valores [S - SE DA DE BAJA, N - NO SE DA DE BAJA]")
  private String mcaInhCob = null;

  @ApiModelProperty(value = "Marca que indica si la contratacion de la cobertura provoca la necesidad de tener inspeccionado el riesgo. Posibles valores [S - INSPECCIONADO, N - NO INSPECCIONADO]")
  private String mcaInsp = null;

  @ApiModelProperty(value = "Marca que indica si se puede modificar la franquicia. Posibles valores [S - SE PUEDE MODIFICAR, N - NO SE PUEDE MODIFICAR]")
  private String mcaModFranquicia = null;

  @ApiModelProperty(value = "Marca que indica si se puede modificar la suma asegurada de la cobertura. Posibles valores [S - PUEDE MODIFICARSE, N - NO PUEDE MODIFICARSE]")
  private String mcaModImpCap = null;

  @ApiModelProperty(value = "Marca que indica si en suplementos se desea respetar el capital de la cobertura o ejecutar de nuevo el procedimiento pre-capital o dependencia de cobertura. Posibles valores [S - SE RESPETA EL CAPITAL, N - NO SE RESPETA EL CAPITAL]")
  private String mcaNuevaImpCap = null;

  @ApiModelProperty(value = "Marca que indica si es obligatorio. Posibles valores [S - OBLIGATORIO, N - NO OBLIGATORIO]")
  private String mcaObl = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura tiene o no reaseguro. Posibles valores [S - TIENE REASEGURO, N - NO TIENE REASEGURO]")
  private String mcaRea = null;

  @ApiModelProperty(value = "Marca de que indica si es actualizable. Posibles valores [S - ACTUALIZABLE, N - NO ACTUALIZABLE]")
  private String mcaSalto = null;

  @ApiModelProperty(value = "Clausula seleccionada. Posibles valores [S - SELECCIONADA, N - NO SELECCIONADA]")
  private String mcaSeleccion = null;

  @ApiModelProperty(value = "Clausula seleccionada anterior. Posibles valores [S - SELECCIONADA, N - NO SELECCIONADA]")
  private String mcaSeleccionAnt = null;

  @ApiModelProperty(value = "Marca de validacion de la cobertura. Posibles valores [S - VALIDA, N - NO VALIDA]")
  private String mcaValidaImpCap = null;

  @ApiModelProperty(value = "Marca que indica si la cobertura tiene un vigencia independiente al riesgo/poliza. Posibles valores [S - VIGENTE, N - NO VIGENTE]")
  private String mcaVigenciaPropia = null;

  @ApiModelProperty(value = "Mes base para la regularizacion de capitales en renovacion")
  private Integer mesBaseRevaloriza = null;

  @ApiModelProperty(value = "Nombre de campo. Posibles valores en la tabla [[TRON.EMIS.DATOS_VARIABLES_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCampo = null;

  @ApiModelProperty(value = "Nombre  de la compania. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "Descripcion reducida de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCob = null;

  @ApiModelProperty(value = "Descripcion del codigo de cobertura relacionada (dependientes e independientes). Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCobRel = null;

  @ApiModelProperty(value = "Descripcion del codigo de agrupamiento")
  private String nomCodGrpAcc = null;

  @ApiModelProperty(value = "Descripcion de la franquicia")
  private String nomFranquicia = null;

  @ApiModelProperty(value = "Descripcion del codigo de la franquicia de origen")
  private String nomFranquiciaOrigen = null;

  @ApiModelProperty(value = "Nombre de agrupamiento 1 de coberturas")
  private String nomGrpCob1 = null;

  @ApiModelProperty(value = "Nombre de agrupamiento 2 de coberturas .")
  private String nomGrpCob2 = null;

  @ApiModelProperty(value = "Nombre de agrupamiento 3 de coberturas .")
  private String nomGrpCob3 = null;

  @ApiModelProperty(value = "Nombre de agrupamiento 4 de coberturas .")
  private String nomGrpCob4 = null;

  @ApiModelProperty(value = "Nombre del indice. Posibles valores en la tabla [[TRON.EMIS.INDICES_REFERENCIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomIndice = null;

  @ApiModelProperty(value = "Descripcion del limite")
  private String nomLimite = null;

  @ApiModelProperty(value = "Nombre limite de origen")
  private String nomLimiteOrigen = null;

  @ApiModelProperty(value = "Nombre de lista de ocurrencias")
  private String nomListaOcu = null;

  @ApiModelProperty(value = "Descripcion de codigo de moneda del capital. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomMonImpCap = null;

  @ApiModelProperty(value = "Nombre del procedimiento de obtencion de la franquicia por defecto.")
  private String nomPrgPreFranquicia = null;

  @ApiModelProperty(value = "Nombre del procedimiento pre-cobertura")
  private String nomPrgPreImpCap = null;

  @ApiModelProperty(value = "En caso de revalorizar por objeto, este campo indica el nombre del objeto")
  private String nomPrgRevalorizaEsp = null;

  @ApiModelProperty(value = "Procedimiento que va a poder validar cuando se acepte el aviso")
  private String nomPrgValida = null;

  @ApiModelProperty(value = "Nombre de procedimiento de validacion para la cobertura")
  private String nomPrgValidaImpCap = null;

  @ApiModelProperty(value = "Nombre del ramo contable")
  private String nomRamoCtable = null;

  @ApiModelProperty(value = "Descripcion de la accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccionBatchEm = null;

  @ApiModelProperty(value = "Descripcion del tipo de cobertura. Posibles valores en la tabla [[TRON.TPES.TIP_COB]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipCob = null;

  @ApiModelProperty(value = "Descripcion del tipo de franquicia. Posibles valores en la tabla [[TRON.TPES.TIP_FRANQUICIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipFranquicia = null;

  @ApiModelProperty(value = "Descripcion del codigo de moneda del capital. Posibles valores en la tabla [[TRON.TPES.TIP_IMP_CAP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipImpCap = null;

  @ApiModelProperty(value = "Descripcion del nivel de la cobertura. Posibles valores en la tabla [[TRON.TPES.TIP_NIVEL_COB]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipNivelCob = null;

  @ApiModelProperty(value = "Descripcion del tipo de refresco en frontal. Posibles valores [1 - REFRESCO SA, 2 - REFRESCO OD]")
  private String nomTipRefresco = null;

  @ApiModelProperty(value = "Descripcion que indica si revaloriza o no en la renovacion (1) no regulariza (2) especial (3) riesgo. Posibles valores en la tabla [[TRON.TPES.TIP_REVALORIZA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipRevaloriza = null;

  @ApiModelProperty(value = "Marca que indica el tipo de revalorizacion. Posibles valores en la tabla [[TRON.TPES.TIP_REVALORIZA_ESP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipRevalorizaEsp = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de periodo")
  private Integer numPeriodo = null;

  @ApiModelProperty(value = "Numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Numero sumas aseguradas o limites iguales")
  private Integer numSaLimIguales = null;

  @ApiModelProperty(value = "Secuencia de la fila")
  private Integer numSecu = null;

  @ApiModelProperty(value = "Nnúmero identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Porcentaje de participacion")
  private BigDecimal pctImpCap = null;

  @ApiModelProperty(value = "Porcentaje de revalorizacion")
  private BigDecimal pctRevalorizaEsp = null;

  @ApiModelProperty(value = "Tasa")
  private BigDecimal tasaCob = null;

  @ApiModelProperty(value = "Accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionBatchEm = null;

  @ApiModelProperty(value = "Tipo de cobertura. Posibles valores en la tabla [[TRON.TPES.TIP_COB]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCob = null;

  @ApiModelProperty(value = "Tipo de franquicia o deducible. Posibles valores en la tabla [[TRON.TPES.TIP_FRANQUICIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipFranquicia = null;

  @ApiModelProperty(value = "Tipo de capital de la cobertura. Posibles valores en la tabla [[TRON.TPES.TIP_IMP_CAP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipImpCap = null;

  @ApiModelProperty(value = "Nivel de la cobertura. Posibles valores en la tabla [[TRON.TPES.TIP_NIVEL_COB]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipNivelCob = null;

  @ApiModelProperty(value = "Tipo de refresco en frontal. Posibles valores [1 - REFRESCO SA, 2 - REFRESCO OD]")
  private String tipRefresco = null;

  @ApiModelProperty(value = "Indica si revaloriza o no en la renovacion (1) no regulariza (2) especial (3) riesgo. Posibles valores en la tabla [[TRON.TPES.TIP_REVALORIZA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipRevaloriza = null;

  @ApiModelProperty(value = "Tipo de revalorizacion. Posibles valores en la tabla [[TRON.TPES.TIP_REVALORIZA_ESP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipRevalorizaEsp = null;

  @ApiModelProperty(value = "Condiciones de la contratacion")
  private String txtCondContrat = null;

  @ApiModelProperty(value = "Condiciones de obligatoriedad")
  private String txtCondObl = null;

  @ApiModelProperty(value = "")
  private String txtImpCap = null;

  @ApiModelProperty(value = "Valor de la franquicia")
  private Integer valFranquicia = null;

  @ApiModelProperty(value = "Importe maximo de franquicia")
  private Integer valFranquiciaMax = null;

  @ApiModelProperty(value = "Valor maximo de la franquicia de origen")
  private Integer valFranquiciaMaxOrigen = null;

  @ApiModelProperty(value = "Importe minimo de franquicia")
  private Integer valFranquiciaMin = null;

  @ApiModelProperty(value = "Valor minimo de la franquicia de origen")
  private Integer valFranquiciaMinOrigen = null;



}

