/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestPlzEmIntervS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestPlzEmIntervS {
  @ApiModelProperty(value = "Abreviatura de la intervencion")
  private String abrInterv = null;

  @ApiModelProperty(value = "Primer apellido del tercero")
  private String ape1Tercero = null;

  @ApiModelProperty(value = "Segundo apellido del tercero")
  private String ape2Tercero = null;

  @ApiModelProperty(value = "Codigo de actividad del tercero de acceso. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codActTercero = null;

  @ApiModelProperty(value = "Codigo compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo de documento")
  private String codDocum = null;

  @ApiModelProperty(value = "Tipo de gestor de cobro. Posibles valores en la tabla [[TRON.TESO.GESTORES_COBROS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codGestor = null;

  @ApiModelProperty(value = "Tipo de gestor de cobro alternativo. Posibles valores en la tabla [[TRON.TESO.GESTORES_COBROS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codGestorAlter = null;

  @ApiModelProperty(value = "Codigo de la identificacion")
  private String codIdentificacion = null;

  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Código del tipo de intervención forma de actuacion del agente. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codInterv = null;

  @ApiModelProperty(value = "Tipo que se utiliza como referencia a la hora de dar de alta. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIntervRef = null;

  @ApiModelProperty(value = "Codigo sector. Posibles valores en la tabla [[TRON.DATC.SECTORES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codSector = null;

  @ApiModelProperty(value = "Contacto completo")
  private String contactoCompleto = null;

  @ApiModelProperty(value = "Cuenta completa")
  private String cuentaCompleto = null;

  @ApiModelProperty(value = "Cuenta completa alternativa")
  private String cuentaCompletoAlter = null;

  @ApiModelProperty(value = "Direccion completa")
  private String dirCompleto = null;

  @ApiModelProperty(value = "Fecha vencimiento de la cesion de derechos. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoCesion = null;

  @ApiModelProperty(value = "Importe de la cesion")
  private BigDecimal impCesion = null;

  @ApiModelProperty(value = "Licencia completa")
  private String licenciaCompleto = null;

  @ApiModelProperty(value = "Marca que indica si se deben dar de baja los beneficiarios cuando el programa los salte en lugar de pedirlos. Posibles valores [S - DAR DE BAJA, N - NO DAR DE BAJA]")
  private String mcaBajaBenef = null;

  @ApiModelProperty(value = "Marca que indica si los calculos se han realizado por este tercero. Posibles valores [S - REALIZADOS, N - NO REALIZADOS]")
  private String mcaCal = null;

  @ApiModelProperty(value = "Marca que indica si se requiere la informacion de cesion de derechos. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaCesion = null;

  @ApiModelProperty(value = "Marca que indica si se permite duplicidad para el tipo de intervención. Posibles valores [S - SE PERMITE, N - NO SE PERMITE]")
  private String mcaDupTercero = null;

  @ApiModelProperty(value = "Marca que indica indica si se usa o no en emision. Posibles valores [S - SE USA, N - NO SE USA]")
  private String mcaEm = null;

  @ApiModelProperty(value = "Marca que indica si el tercero es fisico o juridico. Posibles valores en la tabla [[TRON.TPES.MCA_FISICO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String mcaFisico = null;

  @ApiModelProperty(value = "Marca de baja. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Marca que indica si es quien paga. Posibles valores [S - PAGADOR, N - NO PAGADOR]")
  private String mcaPagador = null;

  @ApiModelProperty(value = "Marca que indica si se requiere el porcentaje en el tipo de tercero. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaPct = null;

  @ApiModelProperty(value = "Marca que indica si es requerido antes o despues de los datos variables a nivel de riesgo. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaPreRiesgo = null;

  @ApiModelProperty(value = "Marca que indica el tercero principal. Posibles valores [S - PRINCIPAL, N - NO PRINCIPAL]")
  private String mcaPrincipal = null;

  @ApiModelProperty(value = "Marca que indica si se requiere medio de contacto. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaSecContacto = null;

  @ApiModelProperty(value = "Marca que indica si se requiere direccion. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaSecDir = null;

  @ApiModelProperty(value = "Marca que indica si se requiere licencia. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaSecLicencia = null;

  @ApiModelProperty(value = "Marca que indica si se requiere medio de pago. Posibles valores [S - SE REQUIERE, N - NO SE REQUIERE]")
  private String mcaSecMedio = null;

  @ApiModelProperty(value = "Marca que indica si se trata de la intervención que se debe mostrar en siniestros. Posibles valores [S - SE DEBE MOSTRAR, N - NO SE DEBE MOSTRAR]")
  private String mcaSini = null;

  @ApiModelProperty(value = "Marca que indica si el porcentaje debe sumar 100 en todo para el tipo de tercero. Posibles valores [S - DEBE SUMAR 100, N - NO DEBE SUMAR 100]")
  private String mcaSuma100 = null;

  @ApiModelProperty(value = "Descripcion del codigo de actividad del tercero de acceso")
  private String nomActTercero = null;

  @ApiModelProperty(value = "Descripcion compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "Descripcion del codigo de la identificacion")
  private String nomCodIdentificacion = null;

  @ApiModelProperty(value = "Nombre completo")
  private String nomCompleto = null;

  @ApiModelProperty(value = "Nombre gestor. Posibles valores en la tabla [[TRON.TESO.GESTORES_COBROS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomGestor = null;

  @ApiModelProperty(value = "Descripcion del gestor alternativo. Posibles valores en la tabla [[TRON.TESO.GESTORES_COBROS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomGestorAlter = null;

  @ApiModelProperty(value = "Descripcion de la intervencion. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomInterv = null;

  @ApiModelProperty(value = "Descripcion del tipo que se utiliza como referencia a la hora de dar de alta. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomIntervRef = null;

  @ApiModelProperty(value = "Procedimiento que determina el porcentaje en el tipo de tercero")
  private String nomPrgPct = null;

  @ApiModelProperty(value = "Procedimiento que determina si el tipo de beneficiario se debe de peticionar o no")
  private String nomPrgPreInterv = null;

  @ApiModelProperty(value = "Referencia a la hora de dar de alta")
  private String nomPrgRef = null;

  @ApiModelProperty(value = "Descripcion del sector. Posibles valores en la tabla [[TRON.DATC.SECTORES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomSector = null;

  @ApiModelProperty(value = "Nombre tercero")
  private String nomTercero = null;

  @ApiModelProperty(value = "Descripcion de la accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccionBatchEm = null;

  @ApiModelProperty(value = "Descripcion del tipo de documento. Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipDocum = null;

  @ApiModelProperty(value = "Descripcion del tipo de intervencion para terceros de emision. Posibles valores en la tabla [[TRON.TPES.TIP_INTERV]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipInterv = null;

  @ApiModelProperty(value = "Numero aplicacion")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de intervinientes con valor nulo, puede ser cualquiera. con numero, minimo 1 maximo el numero indicado en la columna")
  private Integer numInterv = null;

  @ApiModelProperty(value = "Numero minimo de intervenciones")
  private Integer numMinInterv = null;

  @ApiModelProperty(value = "Numero periodo")
  private Integer numPeriodo = null;

  @ApiModelProperty(value = "Numero poliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero del prestamo")
  private String numPrestamo = null;

  @ApiModelProperty(value = "Numero riesgo")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Numero de secuencia")
  private Integer numSecu = null;

  @ApiModelProperty(value = "Numero suplemento")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Numero suplemento aplicacion")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Porcentaje de participacion")
  private BigDecimal pctParticipaInterv = null;

  @ApiModelProperty(value = "Secuencia de la dirección")
  private Integer secDir = null;

  @ApiModelProperty(value = "Secuencia de la licencia ( orden )")
  private Integer secLicencia = null;

  @ApiModelProperty(value = "Número de orden del teléfono")
  private Integer secMedioContacto = null;

  @ApiModelProperty(value = "Secuencia del medio de pago/cobro")
  private Integer secMedioPagocob = null;

  @ApiModelProperty(value = "Medio de pago alternativo")
  private Integer secMedioPagocobAlter = null;

  @ApiModelProperty(value = "Accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionBatchEm = null;

  @ApiModelProperty(value = "Tipo documento. Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDocum = null;

  @ApiModelProperty(value = "Tipo de intervencion para terceros de emision. Posibles valores en la tabla [[TRON.TPES.TIP_INTERV]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipInterv = null;

  @ApiModelProperty(value = "Codigo de gestor de cobro")
  private String valGestor = null;

  @ApiModelProperty(value = "Código de gestor de cobro alternativo")
  private String valGestorAlter = null;



}

