/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestPlzSatSptoPptaS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestPlzSatSptoPptaS {
  @ApiModelProperty(value = "Codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Código del condicionado general. Posibles Valores en la tabla [[TRON.EMIS.CONDICIONADO_GENERAL_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codGeneral = null;

  @ApiModelProperty(value = "Centro de gestion")
  private String codIntElemGest = null;

  @ApiModelProperty(value = "Codigo de poblacion de firma")
  private String codPoblacionFirma = null;

  @ApiModelProperty(value = "Tipificacion de la agrupacion. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_AGRUP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipAgrupacion = null;

  @ApiModelProperty(value = "Codigo que identifica el colectivo que mecaniza la operacion. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_CANAL_SOPORTE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipCanalSoporte = null;

  @ApiModelProperty(value = "Codigo que identifica el frontal/aplicacion desde la que se mecaniza la operacion. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_PLATAFORMA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipPlataforma = null;

  @ApiModelProperty(value = "Tipo de procedencia. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_PROCEDENCIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipProcedencia = null;

  @ApiModelProperty(value = "Usuario que crea/actualiza el registro")
  private String codUsr = null;

  @ApiModelProperty(value = "Código de provincia de la firma")
  private Integer codZona2Firma = null;

  @ApiModelProperty(value = "Codigo de localidad de la firma.")
  private Integer codZona3Firma = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha de caducidad del proyecto/propuesta. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecCaducidad = null;

  @ApiModelProperty(value = "Fecha de compromiso. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecCompromiso = null;

  @ApiModelProperty(value = "Fecha de consulta sobre los diferentes elementos que forman la version de un producto(versión del ramo, versión del acuerdo, versión de tarifa, versión de control técnico..). Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecCondicion = null;

  @ApiModelProperty(value = "Fecha de firma del contrato. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecFirma = null;

  @ApiModelProperty(value = "Fecha que indica la version de producto con la que se ha generado el suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecGlobal = null;

  @ApiModelProperty(value = "Fecha que indica la version global con la que se ha tarificado el suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecGlobalTarifa = null;

  @ApiModelProperty(value = "Fecha de mecanización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecMecanizacion = null;

  @ApiModelProperty(value = "Idenficacion de la agrupacion")
  private String idnAgrupacion = null;

  @ApiModelProperty(value = "Marca que indica si el mensaje es un aviso. Posibles valores [S - ES UN AVISO, N - NO ES UN AVISO]")
  private String mcaAviso = null;

  @ApiModelProperty(value = "Marca que indica si se va a constituir reserva de prima o no. Posibles valores [S - CONSTITUYE RESERVA DE PRIMA, N - NO COSTITUYE RESERVA DE PRIMA]")
  private String mcaConstituDto = null;

  @ApiModelProperty(value = "Marca que indica si se debe o no realizar la devolución de prima. Posibles valores [S - SE DEBE REALIZAR, N - NO SE DEBE REALIZAR]")
  private String mcaDevolucionPrima = null;

  @ApiModelProperty(value = "Marca que indica si se ha modificado manualmente la fecha de condicion. Posibles valores [S - MODIFICADO MANUALMENTE, N - NO MODIFICADO MANUALMENTE]")
  private String mcaFecCondMan = null;

  @ApiModelProperty(value = "Marca que indica si ha sido modificada manualmente la fecha de firma.. Posibles valores [S - MODIFICADA, N - NO MODIFICADA]")
  private String mcaFecFirmaManual = null;

  @ApiModelProperty(value = "Nombre  de la compania. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "Descripcion de tipificacion de la agrupacion. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_AGRUP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipAgrupacion = null;

  @ApiModelProperty(value = "Descripcion que identifica el colectivo que mecaniza la operacion. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_CANAL_SOPORTE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipCanalSoporte = null;

  @ApiModelProperty(value = "Descripcion que identifica el frontal/aplicacion desde la que se mecaniza la operacion. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_PLATAFORMA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipPlataforma = null;

  @ApiModelProperty(value = "Descripcion del código de provincia de la firma")
  private String nomCodZona2Firma = null;

  @ApiModelProperty(value = "Descripcion del codigo de localidad de la firma.")
  private String nomCodZona3Firma = null;

  @ApiModelProperty(value = "Descripción del condicionado general. Posibles Valores en la tabla [[TRON.EMIS.CONDICIONADO_GENERAL_CIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomGeneral = null;

  @ApiModelProperty(value = "Descripcion del codigo de poblacion de firma")
  private String nomPoblacionFirma = null;

  @ApiModelProperty(value = "Descripcion del estado de la operacion. Posibles valores en la tabla [[TRON.TPES.TIP_EST_OPER]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipEstOper = null;

  @ApiModelProperty(value = "Descripcion del nivel global de autorizacion de los controles tecnicos. Posibles valores en la tabla [[TRON.TPES.TIP_GLOBAL_AUTORIZA_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipGlobalAuto = null;

  @ApiModelProperty(value = "Descripcion del tipo de procedencia. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_PROCEDENCIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipProcedencia = null;

  @ApiModelProperty(value = "Descripcion del resultado del control tecnico. Posibles valores en la tabla [[TRON.TPES.TIP_RESULT_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipResultCt = null;

  @ApiModelProperty(value = "Descripcion del tipo de suscripcion del control tecnico. Posibles valores en la tabla [[TRON.TPES.TIP_SUSCRIPCION_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipSuscripCt = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de operacion origen. albergara la situacion de la poliza de la que parte el suplemento")
  private String numOperOrigen = null;

  @ApiModelProperty(value = "Numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de presupuesto si la poliza se realizo a partir de un presupuesto")
  private String numPresupuesto = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Numero de suplemento origen. albergara la situacion de la poliza de la que parte el suplemento")
  private Integer numSptoOrigen = null;

  @ApiModelProperty(value = "Numero de suplemento de referencia. albergara el numero de suplemento seleccionado a partir del cual se quiere anular todos los suplementos posteriores de la poliza.")
  private Integer numSptoRef = null;

  @ApiModelProperty(value = "Porcentaje temporalidad")
  private BigDecimal pctTemporalidad = null;

  @ApiModelProperty(value = "Estado de la operacion. Posibles valores en la tabla [[TRON.TPES.TIP_EST_OPER]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipEstOper = null;

  @ApiModelProperty(value = "Nivel global de autorizacion de los controles tecnicos. Posibles valores en la tabla [[TRON.TPES.TIP_GLOBAL_AUTORIZA_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipGlobalAutorizaCt = null;

  @ApiModelProperty(value = "Resultado del control tecnico. Posibles valores en la tabla [[TRON.TPES.TIP_RESULT_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipResultCt = null;

  @ApiModelProperty(value = "Tipo de suscripcion del control tecnico. Posibles valores en la tabla [[TRON.TPES.TIP_SUSCRIPCION_CT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSuscripCt = null;

  @ApiModelProperty(value = "Observaciones no interés")
  private String txtObsNoInteres = null;



}

