/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestGcCuotaS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestGcCuotaS {
  @ApiModelProperty(value = "Identificador del recibo en reaseguro")
  private Long codCuotaRecibo = null;

  @ApiModelProperty(value = "Codigo cuota del recibo anulado")
  private Long codCuotaReciboAnu = null;

  @ApiModelProperty(value = "Fecha de emisión del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEmSpto = null;

  @ApiModelProperty(value = "Importe de bonificacion")
  private BigDecimal impBoni = null;

  @ApiModelProperty(value = "Importe de comisión")
  private BigDecimal impCom = null;

  @ApiModelProperty(value = "Importe cons")
  private BigDecimal impCons = null;

  @ApiModelProperty(value = "Importe total de la cuota")
  private BigDecimal impCuota = null;

  @ApiModelProperty(value = "Importe de descuento")
  private BigDecimal impDto = null;

  @ApiModelProperty(value = "Importe de impuestos")
  private BigDecimal impImptos = null;

  @ApiModelProperty(value = "Impuestos de los intereses")
  private BigDecimal impImptosInteres = null;

  @ApiModelProperty(value = "Importe de intereses")
  private BigDecimal impInteres = null;

  @ApiModelProperty(value = "Importe neta")
  private BigDecimal impNeta = null;

  @ApiModelProperty(value = "Importe de recargos")
  private BigDecimal impReca = null;

  @ApiModelProperty(value = "Importe total de comisiones")
  private BigDecimal impTotalCom = null;

  @ApiModelProperty(value = "Marca cuota anulada. posibles valores [s - cuota anulada, n - cuota no anulada]")
  private String mcaAnulCuota = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Número de cuota")
  private Integer numCuota = null;

  @ApiModelProperty(value = "Numero de movimiento de emision")
  private Integer numMvtoEm = null;

  @ApiModelProperty(value = "Numero de recibo")
  private Long numRecibo = null;

  @ApiModelProperty(value = "Numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;



}

