/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestPlzIntervAgtS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestPlzIntervAgtS {
  @ApiModelProperty(value = "Abreviatura de la forma de actuacion")
  private String abrIntervAgt = null;

  @ApiModelProperty(value = "Codigo compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Cuadro de comision asignado al agente")
  private String codCuadroCom = null;

  @ApiModelProperty(value = "Código interno del elemento")
  private String codIntElem = null;

  @ApiModelProperty(value = "Forma de intervencion de acceso. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIntervAcceso = null;

  @ApiModelProperty(value = "Forma de intervencion del agente. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIntervAgt = null;

  @ApiModelProperty(value = "Codigo de agente")
  private String codTerceroAgt = null;

  @ApiModelProperty(value = "Tipo de clave que se utiliza en los accesos guiados")
  private String codTipClave = null;

  @ApiModelProperty(value = "Codigo usuario")
  private String codUsr = null;

  @ApiModelProperty(value = "Fecha actualizacion. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha en la que entra en validez la fila. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidezAgt = null;

  @ApiModelProperty(value = "Marca que indica la intervencion con la que se puede emitir")
  private String mcaEm = null;

  @ApiModelProperty(value = "Marca de inhabilitacion. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Marca que indica si ha habido cambio manual en la clave. Posibles valores [S - CAMBIO MANUAL, N - NO CAMBIO MANUAL]")
  private String mcaManualClave = null;

  @ApiModelProperty(value = "Descripcion compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "Descripcion de codigo de agente")
  private String nomCodTerceroAgt = null;

  @ApiModelProperty(value = "Descripcion del tipo de clave que se utiliza en los accesos guiados")
  private String nomCodTipClave = null;

  @ApiModelProperty(value = "Nombre completo")
  private String nomCompleto = null;

  @ApiModelProperty(value = "Descripcion del cuadro de comision asignado al agente")
  private String nomCuadroCom = null;

  @ApiModelProperty(value = "Descripcion de la forma de intervencion de acceso. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomIntervAcceso = null;

  @ApiModelProperty(value = "Descripcion de la forma de intervencion del agente. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomIntervAgt = null;

  @ApiModelProperty(value = "Descripcion de la accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccionBatchEm = null;

  @ApiModelProperty(value = "Descripcion del tipo de calculo de comisiones. Posibles valores en la tabla [[TRON.TPES.TIP_CAL_COM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipCalCom = null;

  @ApiModelProperty(value = "Descripcion del tipo de comision. Posibles valores en la tabla [[TRON.TPES.TIP_COMISION]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipComision = null;

  @ApiModelProperty(value = "Descripcion de la forma de actuacion p,secundario,o,a. Posibles valores en la tabla [[TRON.TPES.TIP_INTERV_AGT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipIntervAgt = null;

  @ApiModelProperty(value = "Numero aplicacion")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de movimiento")
  private Integer numMvtoAgt = null;

  @ApiModelProperty(value = "Numero poliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero suplemento")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Numero suplemento aplicacion")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Porcentaje relativo sobre el agente principal")
  private BigDecimal pctAgt = null;

  @ApiModelProperty(value = "Accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionBatchEm = null;

  @ApiModelProperty(value = "Tipo de calculo de comisiones 1.cuadro 2.%relativo. Posibles valores en la tabla [[TRON.TPES.TIP_CAL_COM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCalCom = null;

  @ApiModelProperty(value = "Tipo de comision. Posibles valores en la tabla [[TRON.TPES.TIP_COMISION]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipComision = null;

  @ApiModelProperty(value = "Forma de actuacion p,secundario,o,a. Posibles valores en la tabla [[TRON.TPES.TIP_INTERV_AGT]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipIntervAgt = null;



}

