/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestGcTerceroS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestGcTerceroS {
  @ApiModelProperty(value = "Primer apellido del tercero")
  private String ape1Tercero = null;

  @ApiModelProperty(value = "Segundo apellido del tercero</")
  private String ape2Tercero = null;

  @ApiModelProperty(value = "Código de actividad de tercero. Posibles valores en la tabla [[TRON.TERC.ACTIVIDADES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codActTercero = null;

  @ApiModelProperty(value = "Código de documento")
  private String codDocum = null;

  @ApiModelProperty(value = "Clave interna del tercero")
  private String codIntTercero = null;

  @ApiModelProperty(value = "Codigo de intervencion del tercero. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codIntervTercero = null;

  @ApiModelProperty(value = "Código Postal")
  private String codPostal = null;

  @ApiModelProperty(value = "Codigo de provincia. Posibles valores para España en la tabla [[TRON.DATC.PROVINCIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codProvincia = null;

  @ApiModelProperty(value = "Código del tercero")
  private String codTercero = null;

  @ApiModelProperty(value = "Código de usuario que realiza la actualización")
  private String codUsr = null;

  @ApiModelProperty(value = "Dirección de e-mail")
  private String dirEmail = null;

  @ApiModelProperty(value = "Direccion")
  private String direccion = null;

  @ApiModelProperty(value = "Fecha de nacimiento")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecNac = null;

  @ApiModelProperty(value = "Marca femenino. Se considera una marca y no un tipo para evitar ambigüedades en otros países. Posibles valores S - Femenino N - Masculino X - Indeterminado")
  private String mcaFemenino = null;

  @ApiModelProperty(value = "Tipo de persona (física o jurídica): - valor S: Persona física - valor N: Persona jurídica")
  private String mcaFisico = null;

  @ApiModelProperty(value = "Descripción del código de actividad de tercero")
  private String nomActTercero = null;

  @ApiModelProperty(value = "Nombre completo del tercero")
  private String nomCompletoTercero = null;

  @ApiModelProperty(value = "Nombre de la persona con la que se va a contactar")
  private String nomContacto = null;

  @ApiModelProperty(value = "Descripción asociada al codigo de intervencion del tercero. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomIntervTercero = null;

  @ApiModelProperty(value = "Localidad. Algunos valores pueden ser: (Con código país = ES y código de zona 2 = 28) 1 - Madrid 53 - Alcalá de Henares 66 - Alcobendas ...")
  private String nomLocalidad = null;

  @ApiModelProperty(value = "Provincia. Posibles valores para España en la tabla [[TRON.DATC.PROVINCIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomProvincia = null;

  @ApiModelProperty(value = "Nombre del tercero. En el caso de tercero jurídico, el nombre se corresponde con el nombre de la empresa")
  private String nomTercero = null;

  @ApiModelProperty(value = "Nombre del tipo de documento Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipDocum = null;

  @ApiModelProperty(value = "Numero de cuenta completo del tercero")
  private String numCuentaCompleto = null;

  @ApiModelProperty(value = "Número de fax")
  private String numFax = null;

  @ApiModelProperty(value = "Número de recibo")
  private Long numRecibo = null;

  @ApiModelProperty(value = "Código del tipo de documento identificativo. Posibles valores en la tabla [[TRON.TERC.DOCUMENTOS_IDENTIFICATIVOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDocum = null;

  @ApiModelProperty(value = "Teléfono móvil")
  private String tlfMovil = null;

  @ApiModelProperty(value = "Número del teléfono")
  private String tlfNum = null;

  @ApiModelProperty(value = "Cuenta completa formato IBAN Electronico")
  private String txtIbanElectronico = null;

  @ApiModelProperty(value = "Cuenta completa formato IBAN")
  private String txtIbanPapel = null;



}

