/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestTrcDdDirAnxS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestTrcDdDirAnxS {
  @ApiModelProperty(value = "Año de apertura de la oficina")
  private Integer anioApert = null;

  @ApiModelProperty(value = "Año en el que el elemento o el delegado pasaron a tomar esta ubicación física.")
  private Integer anioLocActu = null;

  @ApiModelProperty(value = "Código de compañía que accede a este registro de forma exclusiva. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaExclusivo = null;

  @ApiModelProperty(value = "Código de compañía agrupadora. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaGrp = null;

  @ApiModelProperty(value = "Código de compañía titular. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaTitular = null;

  @ApiModelProperty(value = "Código de siete posiciones en el que cada posición representa un día de la semana, si su valor es 1, a ese día se le aplica el horario definido posteriormente y si es 0 no se aplica. Por ejemplo, para representar que el horario normal aplica los lunes, martes, miércoles y jueves, tendrá el valor 1111000.")
  private String codHorario = null;

  @ApiModelProperty(value = "Código de siete posiciones en el que cada posición representa un día de la semana, si su valor es 1, a ese día se le aplica el horario excepcional definido posteriormente y si es 0 no se aplica. Por ejemplo, para representar que el horario excepcional aplica los viernes y sábados, tendrá el valor 0000110.")
  private String codHorarioExcep = null;

  @ApiModelProperty(value = "Código de siete posiciones en el que cada posición representa un día de la semana, si su valor es 1 a ese día se le aplica el horario excepcional en verano definido posteriormente y si es 0 no se aplica. Por ejemplo, para representar que el horario de jornada excepcional de verano aplica los sábados y domingos, tendrá el valor 0000011.")
  private String codHorarioExcepVrn = null;

  @ApiModelProperty(value = "Cada posición representa un día de la semana. horario de verano Código de siete posiciones en el que cada posición representa un día de la semana, si su valor es 1 a ese día se le aplica el horario de verano definido posteriormente y si es 0 no se aplica. Por ejemplo, para representar que el horario de jornada de verano aplica los lunes, martes, miércoles, jueves y viernes, tendrá el valor 1111100.")
  private String codHorarioVrn = null;

  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Actividad a la que se destina el local. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ACT_LOCAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipActLocal = null;

  @ApiModelProperty(value = "Indicador de si se trata de un local en propiedad o de un local alquilado y de si el local es propiedad/alquilado por Mapfre o propiedad/alquilado por el delegado (agente). Posibles valores en la tabla [[TRON.CSTR.COD_TIP_PROPIEDAD]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipPropiedad = null;

  @ApiModelProperty(value = "Tipo de zona donde está ubicada la oficina: Urbana, rural, etc. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ZONA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipZona = null;

  @ApiModelProperty(value = "Día y mes de finalización de la jornada de verano. El formato es DDMM. Por ejemplo: 1509 corresponde con el día 15 de Septiembre.")
  private String fecFinVrn = null;

  @ApiModelProperty(value = "Día y mes de inicio de la jornada de verano. El formato es DDMM. Por ejemplo: 0107 corresponde con el día 1 de Julio.")
  private String fecIniVrn = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada excepcional en jornada de verano. El formato es HHMM. Por ejemplo: 2000 corresponde con las 20:00 h.")
  private String horaFinExcepVrn = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada de mañana habitual. El formato es HHMM. Por ejemplo: 1300 corresponde con las 13:00 h.")
  private String horaFinMna = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada de mañana excepcional. El formato es HHMM. Por ejemplo: 1300 corresponde con las 13:00 h.")
  private String horaFinMnaExcep = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada de mañana verano. El formato es HHMM. Por ejemplo: 1300 corresponde con las 13:00 h.")
  private String horaFinMnaVrn = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada de tarde habitual. El formato es HHMM. Por ejemplo: 2100 corresponde con las 21:00 h.")
  private String horaFinTrd = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada de tarde excepcional. El formato es HHMM. Por ejemplo: 2100 corresponde con las 21:00 h.")
  private String horaFinTrdExcep = null;

  @ApiModelProperty(value = "Hora de finalización de la jornada de tarde verano. El formato es HHMM. Por ejemplo: 2100 corresponde con las 21:00 h.")
  private String horaFinTrdVrn = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada excepcional en jornada de verano El formato es HHMM. Por ejemplo: 0800 corresponde con las 08:00 h.")
  private String horaIniExcepVrn = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada de mañana habitual. El formato es HHMM. Por ejemplo: 0900 corresponde con las 09:00 h.")
  private String horaIniMna = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada de mañana excepcional. El formato es HHMM. Por ejemplo: 0900 corresponde con las 09:00 h.")
  private String horaIniMnaExcep = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada de mañana verano. El formato es HHMM. Por ejemplo: 0900 corresponde con las 09:00 h.")
  private String horaIniMnaVrn = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada de tarde habitual. El formato es HHMM. Por ejemplo: 1500 corresponde con las 15:00 h.")
  private String horaIniTrd = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada de tarde excepcional. El formato es HHMM. Por ejemplo: 1500 corresponde con las 15:00 h.")
  private String horaIniTrdExcep = null;

  @ApiModelProperty(value = "Hora de inicio de la jornada de tarde verano. El formato es HHMM. Por ejemplo: 1500 corresponde con las 15:00 h.")
  private String horaIniTrdVrn = null;

  @ApiModelProperty(value = "Marca de inhabilitación del registro. S - Registro inhabilitado. N - Registro habilitado")
  private String mcaInh = null;

  @ApiModelProperty(value = "Descripción del código de compañía que accede a este registro de forma exclusiva Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaExclusivo = null;

  @ApiModelProperty(value = "Descripción compañía de dato exclusivo. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaGrp = null;

  @ApiModelProperty(value = "Descripción dódigo de compañía titular. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaTitular = null;

  @ApiModelProperty(value = "Descripción actividad a la que se destina el local Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ACT_LOCAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipActLocal = null;

  @ApiModelProperty(value = "Descripción indicador de si se trata de un local en propiedad o de un local alquilado y de si el local es propiedad/alquilado por mapfre o propiedad/alquilado por el delegado (agente). Posibles valores en la tabla [[TRON.CSTR.COD_TIP_PROPIEDAD]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipPropiedad = null;

  @ApiModelProperty(value = "Descripción de tipo de zona donde está ubicada la oficina. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ZONA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipZona = null;

  @ApiModelProperty(value = "Tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccionTrc = null;

  @ApiModelProperty(value = "Observaciones")
  private String obs = null;

  @ApiModelProperty(value = "Secuencia de direccion")
  private Integer secDir = null;

  @ApiModelProperty(value = "Secuencia de direccion anexa")
  private Integer secDirAnx = null;

  @ApiModelProperty(value = "Secuencia de medio de contacto")
  private Integer secMedioContacto = null;

  @ApiModelProperty(value = "Código del tipo de accion sobre el registro del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;



}

