/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestGcReciboS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestGcReciboS {
  @ApiModelProperty(value = "Atributo 1 del recibo")
  private String atrRecibo1 = null;

  @ApiModelProperty(value = "Atributo auxiliar. Nos puede indicar si el recibo se ha enviado al CAT")
  private String atrRecibo2 = null;

  @ApiModelProperty(value = "Referencia entre la tabla de registro de llamadas y una de las tablas de movimientos de recibos.")
  private BigDecimal atrRecibo3 = null;

  @ApiModelProperty(value = "Atributo auxiliar. nos puede indicar el código de gestión que se realiza en el CAT")
  private BigDecimal atrRecibo4 = null;

  @ApiModelProperty(value = "Atributo auxiliar. se puede almacenar el número de referencia de la cta.cte. virtual para transferencias controladas.")
  private String atrRecibo5 = null;

  @ApiModelProperty(value = "Código de causa de tesorería. Posibles valores [[AB - ANU.B.EFEC, AC - ANU.P.CHEQ, AE - ANU.P.EFEC, AG - ANU.GESTIO, AN - ANU.SIN RE, AS - ANU.N.C.SI, CA - ANU.CAM.OF, CO - CAMBIO OFI]]")
  private String codCausaTes = null;

  @ApiModelProperty(value = "Código de compañía. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Código de compañía de cobro. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCiaCobro = null;

  @ApiModelProperty(value = "Código de la gestión de cobro. Posibles valores en la tabla [[TRON.TESO.GESTORES_COBROS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codGestor = null;

  @ApiModelProperty(value = "Código de agrupación del recibo. Posibles valores en la tabla [[TRON.TESO.AGRUP_RECIBOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codGrpRecibo = null;

  @ApiModelProperty(value = "Código de la moneda en que se emite el recibo. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codMon = null;

  @ApiModelProperty(value = "Código del origen del recibo. Posibles valores en la tabla [[TRON.EMIS.ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codOrigenRecibo = null;

  @ApiModelProperty(value = "Codigo de situación del recibo")
  private String codSituRecibo = null;

  @ApiModelProperty(value = "Código de gestión del recibo. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_GESTION_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipGestionRecibo = null;

  @ApiModelProperty(value = "Código del sistema de emisión del recibo.Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipOrigenRecibo = null;

  @ApiModelProperty(value = "Código de usuario que autoriza el control técnico")
  private String codUsrAutoriza = null;

  @ApiModelProperty(value = "Dígito de control")
  private String dgtControl = null;

  @ApiModelProperty(value = "Fecha de la última modificación. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha en la que se autoriza el control técnico. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecAutoriza = null;

  @ApiModelProperty(value = "Fecha efecto del recibo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecRecibo = null;

  @ApiModelProperty(value = "Fecha de emisión del recibo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEm = null;

  @ApiModelProperty(value = "Fecha en la que se debe poner al cobro un recibo. Por defecto, fecha de efecto del recibo. Hay casos que puede ser distinta como los recibos a validar. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecExtraccionRecibo = null;

  @ApiModelProperty(value = "Última fecha de remesa. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecRemesa = null;

  @ApiModelProperty(value = "Fecha real de cambios de estado. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecSituReal = null;

  @ApiModelProperty(value = "Fecha de movimiento. Fecha contable. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecSituRecibo = null;

  @ApiModelProperty(value = "Fecha de cobro. Solo para cobros CT. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVal = null;

  @ApiModelProperty(value = "Fecha límite para el cobro del recibo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoPago = null;

  @ApiModelProperty(value = "Fecha de vencimiento del recibo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoRecibo = null;

  @ApiModelProperty(value = "Importe de descuento")
  private BigDecimal impDtoCheque = null;

  @ApiModelProperty(value = "Importe pendiente")
  private BigDecimal impPdte = null;

  @ApiModelProperty(value = "Importe de impuestos")
  private BigDecimal impPtc = null;

  @ApiModelProperty(value = "Importe total del recibo")
  private BigDecimal impRecibo = null;

  @ApiModelProperty(value = "Importe de RPR")
  private BigDecimal impRpr = null;

  @ApiModelProperty(value = "Marca de constitución de descuento. Posibles valores [Si - si hay descuento, N - no hay descuento]")
  private String mcaConstitucionDto = null;

  @ApiModelProperty(value = "Indica si se puede deducir. Posibles valores [S - si se deduce, N - no se deduce]")
  private String mcaDeduccion = null;

  @ApiModelProperty(value = "Indica si el recibo ha sido enviado al banco. Posibles valores [S - si se ha enviado, N - no se ha enviado]")
  private String mcaEnvio = null;

  @ApiModelProperty(value = "Indica si es modificable. Posibles valores [S - es modificable, N - no es modificable]")
  private String mcaModificable = null;

  @ApiModelProperty(value = "Marca provisional. Posibles valores [S - Provisional, N - No provisional]")
  private String mcaProvisional = null;

  @ApiModelProperty(value = "Nombre causa de tesorería. Posibles valores [[AB - ANU.B.EFEC, AC - ANU.P.CHEQ, AE - ANU.P.EFEC, AG - ANU.GESTIO, AN - ANU.SIN RE, AS - ANU.N.C.SI, CA - ANU.CAM.OF, CO - CAMBIO OFI]]")
  private String nomCausaTes = null;

  @ApiModelProperty(value = "Descripción del código de compañía. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "Descripción del código de compañía de cobro. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCiaCobro = null;

  @ApiModelProperty(value = "Descripción asociada al código de situación del recibo. Posibles valores:")
  private String nomCodSituRecibo = null;

  @ApiModelProperty(value = "Gestión del recibo. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_GESTION_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipGestionRecibo = null;

  @ApiModelProperty(value = "Sistema de emisión del recibo. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipOrigenRecibo = null;

  @ApiModelProperty(value = "Descripción de la gestión de cobro. Posibles valores en la tabla [[TRON.TESO.GESTORES_COBROS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomGestor = null;

  @ApiModelProperty(value = "Descripción asociada al código de agrupación del recibo. Posibles valores en la tabla [[TRON.TESO.AGRUP_RECIBOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomGrpRecibo = null;

  @ApiModelProperty(value = "Descripción asociada al código de la moneda en que se emite el recibo. Posibles valores en la tabla  [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomMon = null;

  @ApiModelProperty(value = "Descripción asociada al código de origen del recibo. Posibles valores en la tabla [[TRON.EMIS.ORIGEN_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomOrigenRecibo = null;

  @ApiModelProperty(value = "Descripción asociada al tipo de actuación del recibo")
  private String nomTipActuacion = null;

  @ApiModelProperty(value = "Descripción de la causa de tesorería. Posibles valores en la tabla [[TRON.TPES.TIP_CAUSA_TES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipCausaTes = null;

  @ApiModelProperty(value = "Descripción asociada a la forma en la que se realiza el cobro del recibo. Posibles valores en la tabla [[TRON.TPES.TIP_PROCESO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipProceso = null;

  @ApiModelProperty(value = "Tipo de recibo. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipRecibo = null;

  @ApiModelProperty(value = "Descripción asociada al tipo situación recibo. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipSituRecibo = null;

  @ApiModelProperty(value = "Número de bloque del parte contable")
  private Long numBloqueTes = null;

  @ApiModelProperty(value = "Número de gestiones por las que ha pasado un recibo")
  private Integer numGestion = null;

  @ApiModelProperty(value = "Número del documento de pago que agrupa recibos")
  private Long numGrpRecibo = null;

  @ApiModelProperty(value = "Número de veces que se ha impreso")
  private Integer numImpresion = null;

  @ApiModelProperty(value = "Número máximo de movimiento del histórico de recibos.")
  private Integer numMvtoRecibo = null;

  @ApiModelProperty(value = "Número de movimiento del recibo grupo")
  private Integer numMvtoReciboGrp = null;

  @ApiModelProperty(value = "Número de orden de pago/cobro")
  private String numOrdPagocob = null;

  @ApiModelProperty(value = "Número de recibo")
  private Long numRecibo = null;

  @ApiModelProperty(value = "Medio de pago del recibo")
  private Integer secMedioPagocob = null;

  @ApiModelProperty(value = "Tipo de actuación del recibo")
  private String tipActuacion = null;

  @ApiModelProperty(value = "Tipo de causa de tesorería. Posibles valores en la tabla [[TRON.TPES.TIP_CAUSA_TES]] del activo RAM Catálogo de Tablas de Núcleo [1.0] ")
  private String tipCausaTes = null;

  @ApiModelProperty(value = "Estado del recibo. Posibles valores [P - Recibo con prima, SP - Recibo sin prima, A - Recibo de agrupación]")
  private String tipEstRecibo = null;

  @ApiModelProperty(value = "Forma en la que se realiza el cobro del recibo. Posibles valores en la tabla [[TRON.TPES.TIP_PROCESO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipProceso = null;

  @ApiModelProperty(value = "Tipo situación recibo. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituRecibo = null;

  @ApiModelProperty(value = "Tipo de cambio a la fecha en que se emite el recibo, si se trata de moneda extranjera. ")
  private BigDecimal valCambio = null;

  @ApiModelProperty(value = "Clave del gestor de cobro")
  private String valGestor = null;



}

