/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestTrcDdIntervS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestTrcDdIntervS {
  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Codigo de intervencion del pagador. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codInterv = null;

  @ApiModelProperty(value = "Marca que indica si afecta. Posibles valores [S - AFECTA, N - NO AFECTA]")
  private String mcaAfecta = null;

  @ApiModelProperty(value = "Descripcion de la intervencion. Posibles valores en la tabla [[TRON.ESTR.INTERVENCIONES_AGENTES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomInterv = null;

  @ApiModelProperty(value = "Descripcion del tipo de accion a realizar con la intervencion del dato modificado del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_INTERV_DATO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccIntervDato = null;

  @ApiModelProperty(value = "Numero de suplemento")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de poliza al que afecta el siniestro")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de riesgo")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Secuencia de la dirección")
  private Integer secDir = null;

  @ApiModelProperty(value = "Secuencia de la licencia ( orden )")
  private Integer secLicencia = null;

  @ApiModelProperty(value = "Numero de orden del telefono")
  private Integer secMedioContacto = null;

  @ApiModelProperty(value = "Secuencia del medio de pago/cobro")
  private Integer secMedioPagocob = null;

  @ApiModelProperty(value = "Tipo de accion a realizar con la intervencion del dato modificado del tercero. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_INTERV_DATO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionIntervDato = null;



}

