/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestPlzEmInfGeneralS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestPlzEmInfGeneralS {
  @ApiModelProperty(value = "Número máximo de renovaciones que tendrá la póliza")
  private Integer cantRenovaciones = null;

  @ApiModelProperty(value = "Codigo canal. Posibles valores en la tabla [[TRON.ESTR.CANAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCanal = null;

  @ApiModelProperty(value = "Causa del suplemento. Posibles valores en la tabla [[TRON.EMIS.CAUSA_SUPLEMENTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codCausaSpto = null;

  @ApiModelProperty(value = "Código compañía. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Cuadro de distribucion del coaseguro")
  private String codCuadroCoa = null;

  @ApiModelProperty(value = "Detalle del suplemento")
  private String codDetSpto = null;

  @ApiModelProperty(value = "Nivel 1 de la estructura")
  private String codElemNivel1 = null;

  @ApiModelProperty(value = "Nivel 10 de la estructura")
  private String codElemNivel10 = null;

  @ApiModelProperty(value = "Nivel 2 de la estructura")
  private String codElemNivel2 = null;

  @ApiModelProperty(value = "Nivel 3 de la estructura")
  private String codElemNivel3 = null;

  @ApiModelProperty(value = "Nivel 4 de la estructura")
  private String codElemNivel4 = null;

  @ApiModelProperty(value = "Nivel 5 de la estructura")
  private String codElemNivel5 = null;

  @ApiModelProperty(value = "Nivel 6 de la estructura")
  private String codElemNivel6 = null;

  @ApiModelProperty(value = "Nivel 7 de la estructura")
  private String codElemNivel7 = null;

  @ApiModelProperty(value = "Nivel 8 de la estructura")
  private String codElemNivel8 = null;

  @ApiModelProperty(value = "Nivel 9 de la estructura")
  private String codElemNivel9 = null;

  @ApiModelProperty(value = "Codigo de envio")
  private String codEnvio = null;

  @ApiModelProperty(value = "Codigo del indice de revalorizacion. Posibles valores en la tabla [[TRON.EMIS.INDICES_REFERENCIA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codIndice = null;

  @ApiModelProperty(value = "Elemento de la estructura")
  private String codIntElemCaptura = null;

  @ApiModelProperty(value = "Codigo moneda de la poliza. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codMon = null;

  @ApiModelProperty(value = "Motivo del suplemento. Posibles valores en la tabla [[TRON.EMIS.MOTIVOS_SUPLEMENTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codMotivoSpto = null;

  @ApiModelProperty(value = "Código de nivel 1")
  private String codNivel1 = null;

  @ApiModelProperty(value = "Código de nivel 10")
  private String codNivel10 = null;

  @ApiModelProperty(value = "Código de nivel 2")
  private String codNivel2 = null;

  @ApiModelProperty(value = "Código de nivel 3")
  private String codNivel3 = null;

  @ApiModelProperty(value = "Código de nivel 4")
  private String codNivel4 = null;

  @ApiModelProperty(value = "Código de nivel 5")
  private String codNivel5 = null;

  @ApiModelProperty(value = "Código de nivel 6")
  private String codNivel6 = null;

  @ApiModelProperty(value = "Código de nivel 7")
  private String codNivel7 = null;

  @ApiModelProperty(value = "Código de nivel 8")
  private String codNivel8 = null;

  @ApiModelProperty(value = "Código de nivel 9")
  private String codNivel9 = null;

  @ApiModelProperty(value = "Código de plan de pago. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codPlanPago = null;

  @ApiModelProperty(value = "Codigo de plan de pago anterior. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codPlanPagoAnt = null;

  @ApiModelProperty(value = "Código de ramo. Posibles valores en la tabla [[TRON.EMIS.RAMOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codRamo = null;

  @ApiModelProperty(value = "Código de sector. Posibles valores en la tabla [[TRON.DATC.SECTORES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codSector = null;

  @ApiModelProperty(value = "Codigo del suplementos. Posibles valores en la tabla [[TRON.EMIS.CODIGOS_SUPLEMENTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codSpto = null;

  @ApiModelProperty(value = "Codigo subcanal. Posibles valores en la tabla [[TRON.ESTR.CANAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codSubcanal = null;

  @ApiModelProperty(value = "Codigo subsector. Posibles valores en la tabla [[TRON.DATC.SECTORES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codSubsector = null;

  @ApiModelProperty(value = "Código del tipo de negocio. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_NEGOCIO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipNegocio = null;

  @ApiModelProperty(value = "Nivel de riesgo")
  private String codTipNivelRiesgo = null;

  @ApiModelProperty(value = "Código tipo de origen. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ORIGEN]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipOrigen = null;

  @ApiModelProperty(value = "Código de usuario")
  private String codUsr = null;

  @ApiModelProperty(value = "Fecha de actualización. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecActu = null;

  @ApiModelProperty(value = "Fecha en la que se autorizo el ultimo control tecnico. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecAutoriza = null;

  @ApiModelProperty(value = "Fecha efecto inicial. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecIni = null;

  @ApiModelProperty(value = "Fecha de efecto de la póliza. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecPoliza = null;

  @ApiModelProperty(value = "Fecha de efecto del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecSpto = null;

  @ApiModelProperty(value = "Fecha de emisión inicial de la póliza. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEm = null;

  @ApiModelProperty(value = "Fecha de emisión del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEmSpto = null;

  @ApiModelProperty(value = "Fecha de anulacion del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEmSptoAnul = null;

  @ApiModelProperty(value = "Fecha de validez. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidez = null;

  @ApiModelProperty(value = "Fecha en la que entra en validez la fila. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidezEstr = null;

  @ApiModelProperty(value = "Fecha de validez utilizada para la grabacion de las intervenciones. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecValidezInterv = null;

  @ApiModelProperty(value = "Fecha de vencimiento de la poliza definitivo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoDefinitiva = null;

  @ApiModelProperty(value = "Fecha de vencimiento para el pago de primas. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoPagoPrima = null;

  @ApiModelProperty(value = "Fecha vencimiento de la póliza. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoPoliza = null;

  @ApiModelProperty(value = "Fecha de vencimiento del suplemento. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoSpto = null;

  @ApiModelProperty(value = "Marca que indica si se autoliquida comisiones. Posibles valores [S - SE AUTOLIQUIDA, N - NO SE AUTOLIQUIDA]")
  private String mcaAutoliquidaCom = null;

  @ApiModelProperty(value = "Marca que indica si las comisiones se han hallado de forma manual. Posibles valores [S - COMISIONES MANUAL, N - NO COMISIONES MANUAL]")
  private String mcaComManual = null;

  @ApiModelProperty(value = "Marca que indica si las cuotas se han hallado de forma manual. Posibles valores [S - FORMA MANUAL, N - NO FORMA MANUAL]")
  private String mcaCuotasManual = null;

  @ApiModelProperty(value = "Marca que indica si la poliza lleva primas manuales. Posibles valores [S - PRIMAS MANUALES, N - NO PRIMAS MANUALES]")
  private String mcaDesManual = null;

  @ApiModelProperty(value = "Indica si la clausula podrá ser imprimible o no. . Posibles valores [S - IMPRIMIBLE, N - NO IMPRIMIBLE]")
  private String mcaImp = null;

  @ApiModelProperty(value = "Marca modificacion del cuadro de coaseguro. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModCodCuadroCoa = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo cod_envio. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModCodEnvio = null;

  @ApiModelProperty(value = "Marca de modificacion del codigo de moneda. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModCodMon = null;

  @ApiModelProperty(value = "Marca modificacion del codigo de plan de pago. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModCodPlanPago = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo cod_tip_negocio. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModCodTipNegocio = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo mca_des_manual. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModDesManual = null;

  @ApiModelProperty(value = "Marca que indica si en emision el campo que indica si se calcula a prorrata o escala es modificable. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModProrrata = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo mca_rea_manual. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModReaManual = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo mca_rea_marco. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModReaMarco = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo mca_revaloriza. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModRevaloriza = null;

  @ApiModelProperty(value = "Marca modificacion del tipo de coaseguro. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModTipCoa = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo tip_rea. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModTipRea = null;

  @ApiModelProperty(value = "Marca que indica si puede modificarse campo tip_revaloriza_esp. Posibles valores [S - MODIFICABLE, N - NO MODIFICABLE]")
  private String mcaModTipRevalorizaEsp = null;

  @ApiModelProperty(value = "Marca que indica que el plan de pago solo afecta al suplemento. Posibles valores [S - AFECTA AL SUPLEMENTO, N - NO AFECTA]")
  private String mcaPlanPagoParaSpto = null;

  @ApiModelProperty(value = "Marca que indica si la poliza esta anulada. Posibles valores [S - ANULADA, N - NO ANULADA]")
  private String mcaPolizaAnul = null;

  @ApiModelProperty(value = "Marca de tercero principal. Posibles valores [S - PRINCIPAL, N - NO PRINCIPAL]")
  private String mcaPrincipal = null;

  @ApiModelProperty(value = "Marca que indica si el calculo a prorrata o escala. Posibles valores [S - PRORRATA, N - ESCALA]")
  private String mcaProrrata = null;

  @ApiModelProperty(value = "Marca que indica si movimiento retenido por control tecnico. Posibles valores [S - PROVISIONAL, N - NO PROVISIONAL]")
  private String mcaProvisional = null;

  @ApiModelProperty(value = "Marca que indica si el reaseguro se distribuye manualmente. Posibles valores [S - SE DISTRIBUYE, N - NO SE DISTRIBUYE]")
  private String mcaReaManual = null;

  @ApiModelProperty(value = "Marca que indica si las aplicaciones de transportes se reasegura segun poliza marco. Posibles valores [S - SE REASEGURA, N - NO SE REASEGURA]")
  private String mcaReaMarco = null;

  @ApiModelProperty(value = "Marca que indica si la distribución de reaseguro debe ser por riesgo o a nivel de póliza. Posibles valores [S - RIESGO, N - POLIZA]")
  private String mcaReaRiesgo = null;

  @ApiModelProperty(value = "Marca de recargo. Posibles valores [S - RECARGO, N - NO RECARGO]")
  private String mcaRecargo = null;

  @ApiModelProperty(value = "Marca que indica si la poliza se va a revalorizar cuando se renueve. Posibles valores [S - SE REVALORIZA, N - NO SE REVALORIZA]")
  private String mcaRevaloriza = null;

  @ApiModelProperty(value = "Marca que indica si el suplemento esta anulado. Posibles valores [S - ANULADO, N - NO ABULADO]")
  private String mcaSptoAnul = null;

  @ApiModelProperty(value = "Marca de suplemento temporal. Posibles valores [S - TEMPORAL, N - NO TEMPORAL]")
  private String mcaSptoTmp = null;

  @ApiModelProperty(value = "Nombre canal. Posibles valores en la tabla [[TRON.ESTR.CANAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCanal = null;

  @ApiModelProperty(value = "Nombre de la causa. Posibles valores en la tabla [[TRON.EMIS.CAUSA_SUPLEMENTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCausaSpto = null;

  @ApiModelProperty(value = "Nombre de compañía. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "Nombre de contrato")
  private String nomContrato = null;

  @ApiModelProperty(value = "Nombre del cuadro de coaseguro")
  private String nomCuadroCoa = null;

  @ApiModelProperty(value = "Nombre del detalle del suplemento. Posibles valores en la tabla [[TRON.EMIS.DETALLLE_SUPLEMENTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomDetSpto = null;

  @ApiModelProperty(value = "Descripción del nivel 1 de la estructura")
  private String nomElemNivel1 = null;

  @ApiModelProperty(value = "Descripción del nivel 10 de la estructura")
  private String nomElemNivel10 = null;

  @ApiModelProperty(value = "Descripción del nivel 2 de la estructura")
  private String nomElemNivel2 = null;

  @ApiModelProperty(value = "Descripción del nivel 3 de la estructura")
  private String nomElemNivel3 = null;

  @ApiModelProperty(value = "Descripción del nivel 4 de la estructura")
  private String nomElemNivel4 = null;

  @ApiModelProperty(value = "Descripción del nivel 5 de la estructura")
  private String nomElemNivel5 = null;

  @ApiModelProperty(value = "Descripción del nivel 6 de la estructura")
  private String nomElemNivel6 = null;

  @ApiModelProperty(value = "Descripción del nivel 7 de la estructura")
  private String nomElemNivel7 = null;

  @ApiModelProperty(value = "Descripción del nivel 8 de la estructura")
  private String nomElemNivel8 = null;

  @ApiModelProperty(value = "Descripción del nivel 9 de la estructura")
  private String nomElemNivel9 = null;

  @ApiModelProperty(value = "Nombre de envio")
  private String nomEnvio = null;

  @ApiModelProperty(value = "Nombre del indice")
  private String nomIndice = null;

  @ApiModelProperty(value = "Nombre moneda. Posibles valores en la tabla [[TRON.DATC.MONEDAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomMon = null;

  @ApiModelProperty(value = "Nombre del motivo del suplemento. Posibles valores en la tabla [[TRON.EMIS.MOTIVOS_SUPLEMENTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomMotivoSpto = null;

  @ApiModelProperty(value = "Descripción del nivel 1")
  private String nomNivel1 = null;

  @ApiModelProperty(value = "Descripción del nivel 10")
  private String nomNivel10 = null;

  @ApiModelProperty(value = "Descripción del nivel 2")
  private String nomNivel2 = null;

  @ApiModelProperty(value = "Descripción del nivel 3")
  private String nomNivel3 = null;

  @ApiModelProperty(value = "Descripción del nivel 4")
  private String nomNivel4 = null;

  @ApiModelProperty(value = "Descripción del nivel 5")
  private String nomNivel5 = null;

  @ApiModelProperty(value = "Descripción del nivel 6")
  private String nomNivel6 = null;

  @ApiModelProperty(value = "Descripción del nivel 7")
  private String nomNivel7 = null;

  @ApiModelProperty(value = "Descripción del nivel 8")
  private String nomNivel8 = null;

  @ApiModelProperty(value = "Descripción del nivel 9")
  private String nomNivel9 = null;

  @ApiModelProperty(value = "Nombre de plan de pago. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomPlanPago = null;

  @ApiModelProperty(value = "Nombre de la poliza cliente")
  private String nomPolizaCliente = null;

  @ApiModelProperty(value = "Nombre de la poliza de grupo")
  private String nomPolizaGrupo = null;

  @ApiModelProperty(value = "Nombre ramo. Posibles valores en la tabla [[TRON.EMIS.RAMOS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomRamo = null;

  @ApiModelProperty(value = "Nombre del sector. Posibles valores en la tabla [[TRON.DATC.SECTORES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomSector = null;

  @ApiModelProperty(value = "Nombre del suplemento")
  private String nomSpto = null;

  @ApiModelProperty(value = "Nombre subcanal. Posibles valores en la tabla [[TRON.ESTR.CANAL]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomSubcanal = null;

  @ApiModelProperty(value = "Nombre subsector. Posibles valores en la tabla [[TRON.DATC.SECTORES]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomSubsector = null;

  @ApiModelProperty(value = "Nombre del tipo de acceso a las comisiones. Posibles valores en la tabla [[TRON.TPES.TIP_ACCESO_COM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccesoCom = null;

  @ApiModelProperty(value = "Nombre de tipo de coaseguro")
  private String nomTipCoa = null;

  @ApiModelProperty(value = "Nombre del tipo de cuota inicial. Posibles valores en la tabla [[TRON.TPES.TIP_CUOTA_INI]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipCuotaIni = null;

  @ApiModelProperty(value = "Nombre del temporalidad de la póliza: renovable, temporal, prima única. Posibles valores en la tabla [[TRON.TPES.TIP_DURACION]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipDuracion = null;

  @ApiModelProperty(value = "Nombre del tipo de movimiento. Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipMvtoEm = null;

  @ApiModelProperty(value = "Nombre del tipo de negocio. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_NEGOCIO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipNegocio = null;

  @ApiModelProperty(value = "Nombre del nivel de riesgo")
  private String nomTipNivelRiesgo = null;

  @ApiModelProperty(value = "Nombre del tipo de operacion que se esta gestionando. Posibles valores en la tabla [[TRON.TPES.TIP_OP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipOp = null;

  @ApiModelProperty(value = "Nombre del tipo de origen. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_ORIGEN]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipOrigen = null;

  @ApiModelProperty(value = "Nombre del tipo de poliza. Posibles valores en la tabla [[TRON.TPES.TIP_POLIZA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipPoliza = null;

  @ApiModelProperty(value = "Nombre del tipo de reaseguro. Posibles valores en la tabla [[TRON.TPES.TIP_REA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipRea = null;

  @ApiModelProperty(value = "Nombre tipo de revaloración. Posibles valores en la tabla [[TRON.TPES.TIP_REVALORIZA_ESP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipRevalorizaEsp = null;

  @ApiModelProperty(value = "Nombre de tipo de situacion de la poliza. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_POLIZA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipSituPoliza = null;

  @ApiModelProperty(value = "Nombre del tipo de suplemento. Posibles valores en la tabla [[TRON.TPES.TIP_SPTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipSpto = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de suplemento anulado")
  private Integer numApliAnul = null;

  @ApiModelProperty(value = "Numero de contrato")
  private Integer numContrato = null;

  @ApiModelProperty(value = "Dias de compromiso para propuesta")
  private Integer numDiasComprProp = null;

  @ApiModelProperty(value = "Número de impresiones de la poliza")
  private Integer numImpresion = null;

  @ApiModelProperty(value = "Numero de movimiento de emision para cambio de forma de pago, de agente, etc.")
  private Integer numMvtoEm = null;

  @ApiModelProperty(value = "Número total de periodos de la póliza")
  private Integer numPeriodos = null;

  @ApiModelProperty(value = "Número de poliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de póliza anterior")
  private String numPolizaAnt = null;

  @ApiModelProperty(value = "Número de póliza cliente")
  private String numPolizaCliente = null;

  @ApiModelProperty(value = "Numero de poliza grupo")
  private String numPolizaGrupo = null;

  @ApiModelProperty(value = "Numero de real de la poliza")
  private String numPolizaReal = null;

  @ApiModelProperty(value = "Número de póliza siguiente")
  private String numPolizaSgte = null;

  @ApiModelProperty(value = "Numero de presupuesto si la poliza se realizo a partir de un presupuesto")
  private String numPresupuesto = null;

  @ApiModelProperty(value = "Cantidad de renovaciones realizadas")
  private Integer numRenovaciones = null;

  @ApiModelProperty(value = "Número total de riesgos que ha tenido la póliza")
  private Integer numRiesgos = null;

  @ApiModelProperty(value = "Numero de secuencia")
  private Integer numSecuEstr = null;

  @ApiModelProperty(value = "Numero de secuencia dentro de la poliza grupo")
  private Integer numSecuGrupo = null;

  @ApiModelProperty(value = "Número suplemento")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Numero de suplemento anulado")
  private Integer numSptoAnul = null;

  @ApiModelProperty(value = "Número suplemento aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Numero de suplemento anulado")
  private Integer numSptoApliAnul = null;

  @ApiModelProperty(value = "Número de suplemento de aplicación para impresión")
  private Integer numSptoApliPublico = null;

  @ApiModelProperty(value = "Número de suplemento para impresión")
  private Integer numSptoPublico = null;

  @ApiModelProperty(value = "Observaciones")
  private String obsSpto = null;

  @ApiModelProperty(value = "Porcentaje de revalorizacion")
  private BigDecimal pctRevalorizaEsp = null;

  @ApiModelProperty(value = "Forma de acceder a la comisiones. Posibles valores en la tabla [[TRON.TPES.TIP_ACCESO_COM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccesoCom = null;

  @ApiModelProperty(value = "Tipo coaseguro (0)sin coaseguro (1)cedido (2)aceptado. Posibles valores en la tabla [[TRON.TPES.TIP_COA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCoa = null;

  @ApiModelProperty(value = "Tipo de cuota inicial. Posibles valores en la tabla [[TRON.TPES.TIP_CUOTA_INI]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCuotaIni = null;

  @ApiModelProperty(value = "Duración de la póliza. Posibles valores en la tabla [[TRON.TPES.TIP_DURACION]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDuracion = null;

  @ApiModelProperty(value = "El movimiento se refiere a un cambio de agente (ca) o cambio de forma de pago (cv) o cambio de coaseguro (cc). Posibles valores en la tabla [[TRON.TPES.TIP_MVTO_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipMvtoEm = null;

  @ApiModelProperty(value = "Tipo de operacion que se esta gestionando. Posibles valores en la tabla [[TRON.TPES.TIP_OP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipOp = null;

  @ApiModelProperty(value = "Tipo de póliza. Posibles valores en la tabla [[TRON.TPES.TIP_POLIZA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipPoliza = null;

  @ApiModelProperty(value = "Tipo de reaseguro - cedido - aceptado. Posibles valores en la tabla [[TRON.TPES.TIP_REA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipRea = null;

  @ApiModelProperty(value = "Tipo de revalorizacion. Posibles valores en la tabla [[TRON.TPES.TIP_REVALORIZA_ESP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipRevalorizaEsp = null;

  @ApiModelProperty(value = "Situacion de la poliza. Posibles valores en la tabla [[TRON.TPES.TIP_SITU_POLIZA]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSituPoliza = null;

  @ApiModelProperty(value = "Tipo de suplemento. Posibles valores en la tabla [[TRON.TPES.TIP_SPTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSpto = null;

  @ApiModelProperty(value = "Tipo de cambio")
  private Integer valCambio = null;

  @ApiModelProperty(value = "Valor de la cuota inicial")
  private Integer valCuotaIni = null;



}

