/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestPlzLimiteCobS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestPlzLimiteCobS {
  @ApiModelProperty(value = "codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "codigo de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]]del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCob = null;

  @ApiModelProperty(value = "codigo de limite. Posibles valores: consultar tabla parámetrica 1.1")
  private Integer codLimite = null;

  @ApiModelProperty(value = "marca de inhabilitacion del registro. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "suplemento anulado. Posibles valores [S - ANULADO, N - NO ANULADO]")
  private String mcaSptoAnul = null;

  @ApiModelProperty(value = "suplemento temporal. Posibles valores [S - TEMPORAL, N - NO TEMPORAL]")
  private String mcaSptoTmp = null;

  @ApiModelProperty(value = "marca de vigente. Posibles valores [S - VIGENTE, N - NO VIGENTE]")
  private String mcaVigente = null;

  @ApiModelProperty(value = "nombre  de la compania. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCia = null;

  @ApiModelProperty(value = "descripcion reducida de la cobertura. Posibles valores en la tabla [[TRON.EMIS.COBERTURAS_CIA]]del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCob = null;

  @ApiModelProperty(value = "descripcion limite. Posibles valores: consultar tabla parámetrica 1.1")
  private String nomLimite = null;

  @ApiModelProperty(value = "número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "numero de periodo")
  private Integer numPeriodo = null;

  @ApiModelProperty(value = "numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;



}

