/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * ORestTrcDdNomalterS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class ORestTrcDdNomalterS {
  @ApiModelProperty(value = "Clave interna del tercero")
  private String codInt = null;

  @ApiModelProperty(value = "Tipo de nombre. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_NOM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String codTipNom = null;

  @ApiModelProperty(value = "Marca de inhabilitación. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Nombre alternativo. puede ser el nombre de una  marca comercial una misma empresa puede definirse con distintos nombres. estos nombres se defininen en este campo")
  private String nomAlter = null;

  @ApiModelProperty(value = "Decripcion del tipo de nombre. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_NOM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomCodTipNom = null;

  @ApiModelProperty(value = "Nombre corto del nombre alternativo")
  private String nomCorAlter = null;

  @ApiModelProperty(value = "Descripcion de la accion a realizar con cada registro de datos de terceros. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String nomTipAccionTrc = null;

  @ApiModelProperty(value = "Secuencia de los distintos valores asociados a un tercero")
  private Integer secNom = null;

  @ApiModelProperty(value = "Secuencia de los distintos valores asociados a un tercero de entrada")
  private Integer secNomEnt = null;

  @ApiModelProperty(value = "Secuencial origen, 0 en registro de datos personales (dp)")
  private Integer secOrigen = null;

  @ApiModelProperty(value = "Accion con registro datos de terceros. Posibles valores en la tabla [[TRON.TNTR.TIP_ACCION_TRC]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionTrc = null;



}

