/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.OGnrMensajeAdvertS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcComisionS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcConceptoEcoS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcCuotaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcInstCuotaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcInstReciboS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcPolizaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboGrpS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboPmaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboSinPmaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcTerceroS;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OutAnularSuplemento
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class OutAnularSuplemento {
  @ApiModelProperty(value = "Lista de advertencias")
  private List<OGnrMensajeAdvertS> listaAdvertencias = null;

  @ApiModelProperty(value = "Listado de comisiones")
  private List<ORestGcComisionS> listaComisionesOut = null;

  @ApiModelProperty(value = "Listado de conceptos economicos")
  private List<ORestGcConceptoEcoS> listaConceptosEcoOut = null;

  @ApiModelProperty(value = "Listado de cuotas")
  private List<ORestGcCuotaS> listaCuotasOut = null;

  @ApiModelProperty(value = "Listado de instalación cuotas")
  private List<ORestGcInstCuotaS> listaInstalacionCuotasOut = null;

  @ApiModelProperty(value = "Listado de instalacion recibos")
  private List<ORestGcInstReciboS> listaInstalacionRecibosOut = null;

  @ApiModelProperty(value = "Listado de polizas")
  private List<ORestGcPolizaS> listaPolizasOut = null;

  @ApiModelProperty(value = "Listado de recibos grupo")
  private List<ORestGcReciboGrpS> listaRecibosGrupoOut = null;

  @ApiModelProperty(value = "Listado de recibos")
  private List<ORestGcReciboS> listaRecibosOut = null;

  @ApiModelProperty(value = "Listado de recibos prima")
  private List<ORestGcReciboPmaS> listaRecibosPrimaOut = null;

  @ApiModelProperty(value = "Listado de recibos sin prima")
  private List<ORestGcReciboSinPmaS> listaRecibosSinPrimaOut = null;

  @ApiModelProperty(value = "Listado de recibos")
  private List<ORestGcTerceroS> listaTercerosOut = null;



}

