/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.ORestTrcDdAutdatoS;
import com.capgemini.coedevon.teammanager.prueba.OutCodAlterC;
import com.capgemini.coedevon.teammanager.prueba.OutContactoC;
import com.capgemini.coedevon.teammanager.prueba.OutCuentaC;
import com.capgemini.coedevon.teammanager.prueba.OutDatoPersonalC;
import com.capgemini.coedevon.teammanager.prueba.OutDireccionC;
import com.capgemini.coedevon.teammanager.prueba.OutLicenciaC;
import com.capgemini.coedevon.teammanager.prueba.OutNomAlterC;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OutDDTerceros
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class OutDDTerceros {
  @ApiModelProperty(value = "Autorizacion Dato")
  private ORestTrcDdAutdatoS autDato = null;

  @ApiModelProperty(value = "Datos personal")
  private OutDatoPersonalC datoPersonal = null;

  @ApiModelProperty(value = "Lista de codigos alternativos")
  private List<OutCodAlterC> listaCodalter = null;

  @ApiModelProperty(value = "Lista de contactos")
  private List<OutContactoC> listaContacto = null;

  @ApiModelProperty(value = "Lista de cuentas")
  private List<OutCuentaC> listaCuenta = null;

  @ApiModelProperty(value = "Lista de direcciones")
  private List<OutDireccionC> listaDireccion = null;

  @ApiModelProperty(value = "Lista de licencias")
  private List<OutLicenciaC> listaLicencia = null;

  @ApiModelProperty(value = "Lista Nombre Alternativo")
  private List<OutNomAlterC> listaNomalter = null;



}

