/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.ORestGcInstReciboS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcPolizaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboGrpS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboPmaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcReciboSinPmaS;
import com.capgemini.coedevon.teammanager.prueba.ORestGcTrcReciboS;
import com.capgemini.coedevon.teammanager.prueba.OutCuotaC;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OutReciboC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class OutReciboC {
  @ApiModelProperty(value = "Listado de instalacion recibos")
  private ORestGcInstReciboS instalacionRecibo = null;

  @ApiModelProperty(value = "Listado de cuotas complejo")
  private List<OutCuotaC> listaCuotasC = null;

  @ApiModelProperty(value = "Listado de polizas")
  private ORestGcPolizaS poliza = null;

  @ApiModelProperty(value = "recibo")
  private ORestGcTrcReciboS recibo = null;

  @ApiModelProperty(value = "Listado de recibos grupo")
  private ORestGcReciboGrpS reciboGrupo = null;

  @ApiModelProperty(value = "recibo prima")
  private ORestGcReciboPmaS reciboPrima = null;

  @ApiModelProperty(value = "recibo sin prima")
  private ORestGcReciboSinPmaS reciboSinPrima = null;



}

