/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * PlanPago
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class PlanPago {
  @ApiModelProperty(value = "Abreviatura plan pago")
  private String abrPlanPago = null;

  @ApiModelProperty(value = "Codigo compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Codigo plan de pago. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codPlanPago = null;

  @ApiModelProperty(value = "Codigo de plan de pago anterior. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codPlanPagoAnt = null;

  @ApiModelProperty(value = "Importe de la cuota minima")
  private BigDecimal impCuotaMin = null;

  @ApiModelProperty(value = "Marca de aplicación")
  private String mcaApli = null;

  @ApiModelProperty(value = "Marca que indica si las cuotas deben ser iguales. Posibles valores en la tabla [S - IGUALES, N - NO IGUALES]")
  private String mcaCuotasIguales = null;

  @ApiModelProperty(value = "Marca que indica si este valor aparecerá por defecto. Posibles valores [S - APARECE POR DEFECTO, N - NO APARECE POR DEFECTO]")
  private String mcaDef = null;

  @ApiModelProperty(value = "Marca que indica si en anulacion de suplementos halla de nuevo la fecha base o toma las del suplemento que se desea anular. Posibles valores [S - HALLA FECHA, N - NO HALLA FECHA]")
  private String mcaFecEfecNuevaAs = null;

  @ApiModelProperty(value = "Fila inhabilitada. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Marca de pago unico. Posibles valores [S - PAGO UNICO, N - NO PAGO UNICO]")
  private String mcaPagoUnico = null;

  @ApiModelProperty(value = "Marca de plan de pago de cliente")
  private String mcaPlanPagoCliente = null;

  @ApiModelProperty(value = "Marca que indica que el plan de pago solo afecta al suplemento. Posibles valores [S - AFECTA, N - NO AFECTA]")
  private String mcaPlanPagoParaSpto = null;

  @ApiModelProperty(value = "Distribucion proporcional al tiempo y numero de cuotas. Posibles valores [S - PRORRATEA, N - NO PRORRATEA]")
  private String mcaProrrata = null;

  @ApiModelProperty(value = "Marca que indica si la poliza tiene recargo por fraccionamiento. Posibles valores [S - TIENE RECARGO, N - NO TIENE RECARGO]")
  private String mcaRecargo = null;

  @ApiModelProperty(value = "Marca que indica si admite calculo de cuotas por riesgo. Posibles valores [S - ADMITE CALCULO, N - NO ADMITE CALCULO]")
  private String mcaRiesgo = null;

  @ApiModelProperty(value = "Programa que altera los conceptos economicos (fraccionables) de la cuota calculada antes por la rutina")
  private String nomPrgAlteraCuota = null;

  @ApiModelProperty(value = "Programa que obtiene los dias de la primera cuota y los dias totales para planes con mca_prorrata=s")
  private String nomPrgDiasProrrata = null;

  @ApiModelProperty(value = "Programa que calcula los intereses")
  private String nomPrgInteres = null;

  @ApiModelProperty(value = "Programa que halla el interes de la primera cuota cuando esta no tiene un recibo ya generado como base para anularlo. solo usado en anulaciones totales")
  private String nomPrgInteresAt = null;

  @ApiModelProperty(value = "Procedimiento que determina la forma de distribuir cuando las cuotas no entran en la vigencia")
  private String nomPrgTipDstVcto = null;

  @ApiModelProperty(value = "Numero aplicacion")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero cuotas")
  private Integer numCuotas = null;

  @ApiModelProperty(value = "Numero poliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero suplemento")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Numero suplemento de aplicacion")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Tipo de accion que se desea cuando el importe de las cuotas no llega al minimo definido. Posibles valores en la tabla [[TRON.TPES.TIP_CUOTA_MIN]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipCuotaMin = null;

  @ApiModelProperty(value = "Forma de distribuir las cuotas en anulaciones parciales.  Posibles valores en la tabla [[TRON.TPES.TIP_DST_AP]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDstAp = null;

  @ApiModelProperty(value = "Forma de distribuir las cuotas. Posibles valores en la tabla [[TRON.TPES.TIP_DST_CUOTAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDstCuotas = null;

  @ApiModelProperty(value = "Forma de distribuir las cuotas cuando el indicador de cuotas iguales es igual a ''s''. Posibles valores en la tabla [[TRON.TPES.TIP_DST_CUOTAS_IGU]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDstCuotasIgu = null;

  @ApiModelProperty(value = "Forma de distribucion cuando las cuotas del plan de pago no entran en la vigencia del movimiento. Posibles valores en la tabla [[TRON.TPES.TIP_DST_VCTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipDstVcto = null;

  @ApiModelProperty(value = "Fecha que se toma como base para la generacion de cuotas. Posibles valores en la tabla [[TRON.TPES.TIP_FEC_BASE]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipFecBase = null;

  @ApiModelProperty(value = "Medida que se utilizara para la creacion de los efectos/vencimientos.  Posibles valores en la tabla [[TRON.TPES.TIP_UNIDAD_VCTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipUnidadVcto = null;



}

