/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * PolizasAutorizar
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class PolizasAutorizar {
  @ApiModelProperty(required = true, value = "Código de Compañía. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(required = true, value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(required = true, value = "Número de póliza")
  private String numPoliza = null;

  @ApiModelProperty(required = true, value = "Número de póliza real")
  private String numPolizaReal = null;

  @ApiModelProperty(value = "Número de suplemento de aplicación a partir del que se hará la autorización")
  private Integer numSptoApliDesde = null;

  @ApiModelProperty(required = true, value = "Número de suplemento a partir del que se hará la autorización")
  private Integer numSptoDesde = null;

  @ApiModelProperty(value = "Comentario para la autorización")
  private String observaciones = null;

  @ApiModelProperty(value = "Texto del campo")
  private String txtCampo = null;

  @ApiModelProperty(value = "Valor del campo")
  private String valCampo = null;



}

