/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * RecibosGrupo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class RecibosGrupo {
  @ApiModelProperty(value = "Código de recibo grupo que permite identificar unívocamente el recibo grupo, permitiendo la actualización del numRecibo (en paralelo y por control técnico)")
  private String codReciboGrp = null;

  @ApiModelProperty(value = "Fecha de movimiento del recibo grupo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecMvtoGrp = null;

  @ApiModelProperty(value = "Identificador del plan de pago")
  private String idnPlanPago = null;

  @ApiModelProperty(value = "Marca de anulación del grupo. Posibles valores [S - grupo anulado, N - grupo no anulado]")
  private String mcaAnulGrp = null;

  @ApiModelProperty(value = "Número máximo de movimiento del histórico de recibos.")
  private Integer numMvtoRecibo = null;

  @ApiModelProperty(value = "Número de recibo")
  private Long numRecibo = null;

  @ApiModelProperty(value = "Número total de recibos")
  private Integer numTotalRecibos = null;

  @ApiModelProperty(value = "Tipo de plan de pago del grupo. Posibles valores en la tabla [[TRON.EMIS.PLANES_PAGO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipGrpPlanPago = null;

  @ApiModelProperty(value = "Tipo de recibo grupo. Posibles valores en la tabla [[TRON.CSTR.COD_TIP_RECIBO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipGrpRecibo = null;



}

