/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.IOException;
import java.util.Date;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Riesgo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Riesgo {
  @ApiModelProperty(value = "Codigo de compañia. Posibles valores en la tabla [[TRON.DATC.COMPANIAS]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private Integer codCia = null;

  @ApiModelProperty(value = "Agrupacion de riesgo")
  private Integer codGrpRiesgo = null;

  @ApiModelProperty(value = "Codigo clave ioas")
  private String codIoas = null;

  @ApiModelProperty(value = "Codigo de la modalidad.")
  private Integer codModalidad = null;

  @ApiModelProperty(value = "Fecha de vigencia del riesgo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecEfecRiesgo = null;

  @ApiModelProperty(value = "Fecha de vencimiento del riesgo. Formato de fecha ('yyyy-mm-ddThh:MM:ssZ')")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
  private Date fecVctoRiesgo = null;

  @ApiModelProperty(value = "Marca que indica si genero conceptos de desglose. Posibles valores [S - GENERA CONCEPTOS, N - NO GENERA CONCEPTOS]")
  private String mcaImp = null;

  @ApiModelProperty(value = "Marca de inhabilitacion del registro. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A. ")
  private String mcaInh = "A";

  @ApiModelProperty(value = "Marca de baja del grupo. Esta marca se utilizará para indicar si se solicita recuperar las ocurrencias habilitadas, inhabilitadas o todas: - valor N: Registros habilitados - valor S: Registros inhabilitados - valor A: Ambos. Si se envía vacío, el valor por defecto es A.")
  private String mcaInhGrpRiesgo = "A";

  @ApiModelProperty(value = "Marca que indica si se anula los movimientos realizados al riesgo en un suplemento. Posibles valores [S - ANULA, N - NO ANULA]")
  private String mcaMvtoAnul = null;

  @ApiModelProperty(value = "Descripcion de agrupacion de riesgo")
  private String nomGrpRiesgo = null;

  @ApiModelProperty(value = "Descripcion del riesgo")
  private String nomRiesgo = null;

  @ApiModelProperty(value = "Número de aplicación")
  private Integer numApli = null;

  @ApiModelProperty(value = "Numero de póliza")
  private String numPoliza = null;

  @ApiModelProperty(value = "Numero de riesgo.")
  private Integer numRiesgo = null;

  @ApiModelProperty(value = "Número identificador del suplemento de la póliza")
  private Integer numSpto = null;

  @ApiModelProperty(value = "Número identificador de suplemento de aplicación")
  private Integer numSptoApli = null;

  @ApiModelProperty(value = "Accion a realizar con la fila. Posibles valores en la tabla [[TRON.TPES.TIP_ACCION_BATCH_EM]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipAccionBatchEm = null;

  @ApiModelProperty(value = "Tipo de modalidad del riesgo")
  private String tipModRiesgo = null;

  @ApiModelProperty(value = "Tipo de suplemento. Posibles valores en la tabla [[TRON.TPES.TIP_SPTO]] del activo RAM Catálogo de Tablas de Núcleo [1.0]")
  private String tipSpto = null;



}

