/*
 * Tratar Datos Pólizas (NT21)
 * El servicio descrito en el siguiente documento hace referencia a las operaciones de tratamiento de polizas en la base de datos de tron21.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.capgemini.coedevon.teammanager.prueba;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.capgemini.coedevon.teammanager.prueba.Error;
import com.capgemini.coedevon.teammanager.prueba.StackTrace;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Tron21Error
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-20T06:08:01.090Z")
@Data
@JsonInclude(Include.NON_EMPTY)
public class Tron21Error {
  @ApiModelProperty(required = true, value = "Aplicación donde se ha producido el error")
  private String application = null;

  @ApiModelProperty(required = true, value = "Codigo de error de la operación")
  private String code = null;

  @ApiModelProperty(required = true, value = "Componente donde se ha producido el error")
  private String component = null;

  @ApiModelProperty(value = "Contexto donde se ha producido el error")
  private String context = null;

  @ApiModelProperty(required = true, value = "Datos de la estructura interna de Error")
  private List<Error> errors = new ArrayList<Error>();

  @ApiModelProperty(value = "Excepción que ha producido el error")
  private String exception = null;

  @ApiModelProperty(required = true, value = "Descripción del codigo de error de la operación")
  private String message = null;

  @ApiModelProperty(value = "Datos de la estructura de la pila de llamadas")
  private StackTrace stackTrace = null;

  @ApiModelProperty(required = true, value = "Fecha y hora cuando se ha producido el error")
  private String timestamp = null;

  @ApiModelProperty(required = true, value = "Tipo del error. Los valores pueden ser {F, L, T} F-FUNCTIONAL, L-LOGICAL, T-TECHNICAL")
  private String type = null;



}

